In [1]:
import sqlite3
import requests
import time
import json
import pandas as pd
import urllib.parse
from dotenv import load_dotenv
import os
import datetime
from concurrent.futures import ThreadPoolExecutor

from pathlib import Path

In [2]:
ROOT = Path.cwd().parent

In [3]:
load_dotenv(ROOT / '.env')
ITAD_KEY = os.getenv('ITAD_API_KEY')
DB_PATH = str(ROOT / 'db' / 'gaming_warehouse.db')
ITAD_BASE = 'https://api.isthereanydeal.com'
TIMEOUT   = 15

In [4]:
def crear_tablas():
    with sqlite3.connect(DB_PATH) as conn:

        # Agregar itad_id_texto a CAT_Juego si no existe
        cols = [r[1] for r in conn.execute("PRAGMA table_info(CAT_Juego)").fetchall()]
        if 'itad_id_texto' not in cols:
            conn.execute("ALTER TABLE CAT_Juego ADD COLUMN itad_id_texto TEXT")

        conn.executescript("""
            CREATE TABLE IF NOT EXISTS Hist_Precios_ITAD (
                itad_id_texto TEXT,
                precio_base   REAL,
                precio        REAL,
                descuento     INTEGER,
                fecha_unix    INTEGER,
                PRIMARY KEY (itad_id_texto, fecha_unix)
            );

            CREATE TABLE IF NOT EXISTS Datos_Actuales_ITAD (
                itad_id_texto       TEXT PRIMARY KEY,
                precio_actual       REAL,
                precio_minimo       REAL,
                fecha_minimo        INTEGER,
                en_bundle           INTEGER DEFAULT 0,
                descuento_actual    INTEGER,
                expiry              INTEGER,
                fecha_actualizacion INTEGER
            );
        """)

        # Agregar columnas nuevas a Datos_Actuales_ITAD si no existen
        cols = [r[1] for r in conn.execute("PRAGMA table_info(Datos_Actuales_ITAD)").fetchall()]
        for col, tipo in [("descuento_actual", "INTEGER"), ("expiry", "INTEGER")]:
            if col not in cols:
                conn.execute(f"ALTER TABLE Datos_Actuales_ITAD ADD COLUMN {col} {tipo}")

In [5]:
crear_tablas()

In [ ]:
# Prueba con 10 juegos — ver mapeo antes de insertar
with sqlite3.connect(DB_PATH) as conn:
    muestra = conn.execute("""
        SELECT juego_id, titulo, id_steam
        FROM CAT_Juego
        WHERE id_steam IS NOT NULL
          AND itad_id_texto IS NULL
        LIMIT 10
    """).fetchall()

resultados = []
for juego_id, titulo, id_steam in muestra:
    try:
        res = requests.get(
            f"{ITAD_BASE}/games/lookup/v1",
            params={"key": ITAD_KEY, "appid": id_steam},
            timeout=TIMEOUT
        )
        data = res.json()
        resultados.append({
            "juego_id":juego_id,
            "titulo_db":titulo,
            "id_steam":id_steam,
            "found":data.get("found", False),
            "itad_id":data["game"]["id"]    if data.get("found") else None,
            "titulo_itad": data["game"]["title"] if data.get("found") else None,
        })
    except Exception as e:
        resultados.append({"juego_id": juego_id, "titulo_db": titulo, "id_steam": id_steam, "found": False, "itad_id": None, "titulo_itad": str(e)})
    time.sleep(0.5)

df_mapeo = pd.DataFrame(resultados)
print(f"{df_mapeo['found'].sum()} / {len(df_mapeo)}")
display(df_mapeo)

Encontrados: 10 / 10

,juego_id,titulo_db,id_steam,found,itad_id,titulo_itad
0,1,Grand Theft Auto V,271590,True,018d937f-03e2-7281-a961-037a2d279a92,Grand Theft Auto V
1,2,The Witcher 3: Wild Hunt,292030,True,018d937f-1212-7232-b23f-a046f6fd4a57,The Witcher 3: Wild Hunt
2,3,Portal 2,620,True,018d937f-21e1-728e-86d7-9acb3c59f2bb,Portal 2
3,4,The Elder Scrolls V: Skyrim,72850,True,018d937f-2b23-73a3-9b40-d93860065d00,The Elder Scrolls V: Skyrim
4,5,Grand Theft Auto: San Andreas,12120,True,018d937e-f829-73ff-aa7f-95421948da6b,Grand Theft Auto - San Andreas
5,6,Portal,400,True,018d937f-1749-73f8-bf5a-8e0aa3cdd9ff,Portal
6,7,Red Dead Redemption 2,1174180,True,018d937f-3a3b-7210-bd2d-0d1dfb1d84c0,Red Dead Redemption 2
7,8,God of War,1593500,True,018d937f-4964-7357-a557-f04dac608915,God of War
8,9,Half-Life 2,220,True,018d937f-012f-73b8-ab2c-898516969e6a,Half-Life 2
9,10,BioShock,7670,True,018d937f-00db-709e-9c93-c0c25174ca30,BioShock

In [9]:
def vincular_juegos(limite=100):
    with sqlite3.connect(DB_PATH) as conn:
        pendientes = conn.execute("""
            SELECT juego_id, titulo, id_steam
            FROM CAT_Juego
            WHERE id_steam IS NOT NULL
              AND itad_id_texto IS NULL
            LIMIT ?
        """, (limite,)).fetchall()

    if not pendientes:
        print("Sin pendientes, al fin acabo")
        return 0

    total     = len(pendientes)
    vinculados = 0
    print(f"{total} juegos a vincular")

    for i, (juego_id, titulo, id_steam) in enumerate(pendientes, 1):
        try:
            res = requests.get(
                f"{ITAD_BASE}/games/lookup/v1",
                params={"key": ITAD_KEY, "appid": id_steam},
                timeout=TIMEOUT
            )
            if res.status_code == 429:
                print("limt, esperando 20s")
                time.sleep(20)
                continue

            data = res.json()
            if data.get("found"):
                itad_id = data["game"]["id"]
                with sqlite3.connect(DB_PATH) as conn:
                    conn.execute(
                        "UPDATE CAT_Juego SET itad_id_texto = ? WHERE juego_id = ?",
                        (itad_id, juego_id)
                    )
                vinculados += 1
                print(f"  [{i}/{total}] OK: {titulo} → {itad_id}")
            else:
                print(f"  [{i}/{total}] no encontrado: {titulo}")

        except KeyboardInterrupt:
            print(f"\nInterrumpido en [{i}/{total}]. Vinculados hasta ahora: {vinculados}")
            return vinculados
        except Exception as e:
            print(f"  [{i}/{total}] error [{titulo}]: {e}")
        finally:
            time.sleep(0.5)

    return vinculados

In [10]:
while vincular_juegos(limite=100) > 0:
    time.sleep(2)

100 juegos a vincular
  [1/100] OK: Grand Theft Auto V → 018d937f-03e2-7281-a961-037a2d279a92
  [2/100] OK: The Witcher 3: Wild Hunt → 018d937f-1212-7232-b23f-a046f6fd4a57
  [3/100] OK: Portal 2 → 018d937f-21e1-728e-86d7-9acb3c59f2bb
  [4/100] OK: The Elder Scrolls V: Skyrim → 018d937f-2b23-73a3-9b40-d93860065d00
  [5/100] OK: Grand Theft Auto: San Andreas → 018d937e-f829-73ff-aa7f-95421948da6b
  [6/100] OK: Portal → 018d937f-1749-73f8-bf5a-8e0aa3cdd9ff
  [7/100] OK: Red Dead Redemption 2 → 018d937f-3a3b-7210-bd2d-0d1dfb1d84c0
  [8/100] OK: God of War → 018d937f-4964-7357-a557-f04dac608915
  [9/100] OK: Half-Life 2 → 018d937f-012f-73b8-ab2c-898516969e6a
  [10/100] OK: BioShock → 018d937f-00db-709e-9c93-c0c25174ca30
  [11/100] OK: Assassin's Creed II → 018d937f-3497-71d8-91b5-442e6b36f0cd
  [12/100] OK: Grand Theft Auto: Vice City → 018d937e-f01b-70c9-85e2-52a3122c9560
  [13/100] OK: Half-Life → 018d937f-0bc2-7120-8fb2-a469fde4fcbf
  [14/100] OK: Mass Effect 2 → 018d937f-6d20-7059-905f-15303856b01a
  [15/100] OK: BioShock Infinite → 018d937e-f877-71b3-aba5-8ff11818cd0b
  [16/100] OK: Batman: Arkham City → 018d937f-067b-70c3-901d-b3e01fb740ec
  [17/100] OK: Batman: Arkham Asylum → 018d937f-21ee-71f2-aa66-fe39c68e846a
  [18/100] OK: Mass Effect → 018d937f-4d3f-72ee-b598-97cbfa030c47
  [19/100] OK: Fallout: New Vegas → 018d937f-0896-71b1-94d9-82725d1e320a
  [20/100] OK: Tomb Raider → 018d937e-f9f4-7235-b38c-bfdcb325b577
  [21/100] OK: Far Cry 3 → 018d937e-e9db-717a-baeb-62a6513d146c
  [22/100] OK: Hollow Knight → 018d937f-1ae9-734c-ba47-bd357cf07edd
  [23/100] OK: Elden Ring → 018d937f-590c-728b-ac35-38bcff85f086
  [24/100] OK: Doom → 018d937e-fce8-716b-97f3-6a41f82bb9e7
  [25/100] OK: Dark Souls III → 018d937f-209c-7223-8ead-671a11f25e7e
  [26/100] OK: Dishonored → 018d937e-f96f-71e5-aa80-352cbee965b9
  [27/100] OK: Undertale → 018d937e-efe4-70f0-920b-130e6f0c9d13
  [28/100] OK: Borderlands 2 → 018d937e-f48c-7289-8516-c7c5b2e12eba
  [29/100] OK: Grand Theft Auto IV → 018d937f-1af9-726f-b7fa-fd09622f57f6
  [30/100] OK: Life is Strange → 018d937f-03cf-7371-b83b-3c48b18b76aa
  [31/100] OK: Mass Effect 3 → 018d937f-4e56-7230-a3ca-8f33a69b08de
  [32/100] OK: Call of Duty 4: Modern Warfare → 018d937f-7462-73e3-96df-a80b747306b1
  [33/100] OK: Assassin's Creed IV Black Flag → 018d937f-0602-72cd-b27e-1beaec4b9f6f
  [34/100] OK: Fallout 3 → 018d937f-03d8-729c-8f6d-34d2c739e6ba
  [35/100] OK: Max Payne → 018d937f-0650-7041-83bd-528b3190f299
  [36/100] OK: Stardew Valley → 018d937e-f835-710c-b95b-928e277b187e
  [37/100] OK: Assassin's Creed Brotherhood → 018d937f-0e82-70e5-ac00-0d05a4abc342
  [38/100] OK: The Walking Dead → 018d937e-f05c-7388-88ac-876eacf2e2fd
  [39/100] OK: Fallout 4 → 018d937f-2bba-710d-aa7f-64f220f04817
  [40/100] OK: Dragon Age: Origins → 018d937e-ea23-705b-859a-e014767f5458
  [41/100] OK: Hades → 018d937f-33f0-7200-80fc-87f769196c84
  [42/100] OK: Inside → 018d937f-164a-71af-aabe-21230f3f3f4e
  [43/100] OK: Grand Theft Auto III → 018d937f-223e-7372-9fca-fa02e0652441
  [44/100] OK: Limbo → 018d937e-ea32-7036-ad1c-5f8fb76a7583
  [45/100] OK: The Elder Scrolls IV: Oblivion → 01965e11-4451-728c-9e90-89e3d49f5868
  [46/100] OK: Call of Duty: Modern Warfare 2 → 018d937f-62ef-71e8-990a-e31f12db98ef
  [47/100] OK: Cyberpunk 2077 → 018d937f-2997-7131-b8b9-7c8af4825fa8
  [48/100] OK: Mafia → 018d937f-3102-701d-a896-7cbc7f8bbec8
  [49/100] OK: NieR: Automata → 018d937f-2ee8-7008-bda8-5bc6436d8ae3
  [50/100] OK: Ori and the Blind Forest → 018d937f-20fc-70b0-a991-ef52f6e70bd4
  [51/100] OK: Batman: Arkham Knight → 018d937f-0e0c-70be-91d5-75e399e6b4e3
  [52/100] OK: Assassin's Creed III → 018d937e-e9d4-7075-a482-728448f8f0fc
  [53/100] OK: Half-Life 2: Episode Two → 018d937f-33d5-73be-87f4-56da2c86efa5
  [54/100] OK: Star Wars: Knights of the Old Republic → 018d937e-f856-715d-b4d3-7bc2706ddf8b
  [55/100] OK: Baldur's Gate III → 018d9584-24d6-7010-b82b-df1f0b154cc7
  [56/100] OK: Celeste → 018d937f-1382-7004-b65b-e6adfce11377
  [57/100] OK: Middle-earth: Shadow of Mordor → 018d937f-0a89-7069-a869-1ade408b2d54
  [58/100] OK: Resident Evil 2 → 018d937f-781e-716d-acee-7650541ad533
  [59/100] no encontrado: Counter-Strike: Global Offensive
  [60/100] OK: Rise of the Tomb Raider → 018d937e-f4d8-7368-a624-4a0e38d5d2eb
  [61/100] OK: Call of Duty: Black Ops → 018d937f-357b-70d9-bb51-1ba20521b371
  [62/100] OK: Sekiro: Shadows Die Twice → 018d937f-5599-70de-b7b0-96f7e67684ff
  [63/100] OK: Wolfenstein: The New Order → 018d937f-11e6-715a-a82c-205cfda90ddd
  [64/100] OK: Hotline Miami → 018d937f-1991-707d-9471-9514de905e38
  [65/100] OK: Assassin's Creed Revelations → 018d937f-0085-7156-93a8-5a7c9a7854cf
  [66/100] OK: Detroit: Become Human → 018d937e-f0ad-7094-b86c-d8fb32a1e6b4
  [67/100] OK: Mafia II → 018d937f-4293-7217-a8d5-41fbaeed4613
  [68/100] OK: Dead Space → 018d937f-66a3-7379-b454-b05fe297ae90
  [69/100] OK: Rocket League → 018d937f-0a42-73de-a3a3-e7a08bc728b2
  [70/100] OK: South Park: The Stick of Truth → 018d937e-ea28-7385-82ae-194da55d7217
  [71/100] OK: The Wolf Among Us → 018d937f-0ea6-732e-866d-75df62546c6b
  [72/100] OK: Firewatch → 018d937e-f52e-721f-a1f7-012ad9c06a8b
  [73/100] OK: Left 4 Dead 2 → 018d937f-2404-7297-93fb-94b54bdb74e5
  [74/100] OK: Journey → 018d937f-2dcc-7017-8591-df882109f3e9
  [75/100] OK: Metal Gear Solid V: The Phantom Pain → 018d937e-fa14-7020-9111-93ad90d49695
  [76/100] OK: Sid Meier's Civilization V → 018d937e-fce3-7094-bf5f-033eef93575d
  [77/100] OK: Call of Duty: Modern Warfare 3 → 018d937f-7813-727f-929e-9ca820d9e335
  [78/100] OK: Max Payne 3 → 018d937f-1624-7008-a279-b8bfb6e55610
  [79/100] OK: Far Cry 4 → 018d937e-e9e5-72fa-a1dc-e7e0859183b6
  [80/100] OK: Watch Dogs → 018d937e-f0a4-725f-ad9f-2b5075961980
  [81/100] OK: Disco Elysium → 018d937f-51f4-727c-95c0-ba550d156c86
  [82/100] OK: Heavy Rain → 018d937e-f99a-7194-a303-07dd8f22d0b4
  [83/100] OK: BioShock 2 → 018d937e-ea52-713b-b1d2-963f87211f25
  [84/100] OK: Assassin's Creed Origins → 018d937f-246a-7339-8ccc-7bddae738345
  [85/100] OK: Hellblade: Senua's Sacrifice → 018d937f-0e63-73bc-9df0-bde83d04cb52
  [86/100] OK: Dragon Age: Inquisition → 018d937f-299a-70da-a88b-1914e7ed1594
  [87/100] OK: Battlefield 3 → 018d937f-03b7-718c-afcc-9fccfea4af66
  [88/100] OK: Call of Duty 2 → 018d937f-0393-722e-83ec-3e52af740cf4
  [89/100] OK: Dead Space 2 → 018d937e-f830-72ee-9d74-b58e96c65958
  [90/100] OK: Deus Ex: Human Revolution → 018d937e-ff34-726a-9338-3cd905a49348
  [91/100] OK: L.A. Noire → 018d937f-299c-729c-bc8c-2c990e341c01
  [92/100] OK: Max Payne 2: The Fall of Max Payne → 018d937f-26e9-7058-9337-3957883a16b7
  [93/100] OK: God of War Ragnarök → 018d937f-6bca-706d-9e69-8316170c379b
  [94/100] OK: It Takes Two → 018d937f-4a27-72c8-9837-8ec5e5e92932
  [95/100] OK: Resident Evil 7: Biohazard → 018d937e-fa07-73ce-a8ee-b9fa1e674392
  [96/100] OK: Borderlands → 018d937e-f87b-73bf-a7fc-2cd555ec47a8
  [97/100] OK: Dying Light → 018d937e-f022-7110-a507-755f61a998cc
  [98/100] OK: Terraria → 018d937f-30fa-705e-8a3a-f39719bdde93
  [99/100] OK: Alan Wake → 018d937f-131c-708f-a973-4fc0767e382d
  [100/100] OK: Star Wars Jedi: Fallen Order → 018d937f-2979-72d3-b30e-beb459582423
100 juegos a vincular
  [1/100] no encontrado: Counter-Strike: Global Offensive
  [2/100] OK: The Stanley Parable → 018d937f-060b-7399-9cd9-f894b77fb9a9
  [3/100] OK: What Remains of Edith Finch → 018d937f-00e8-729d-a917-e2f1d5bcc95d
  [4/100] OK: Mirror's Edge → 018d937f-1d10-738e-a02f-67185816bae5
  [5/100] OK: Call of Duty: World at War → 018d937f-1ec4-7327-8a2a-99c60e52cd77
  [6/100] OK: Assassin's Creed Unity → 018d937e-f54c-7379-a57f-9ab6cdc42d20
  [7/100] OK: Assassin's Creed Odyssey → 018d937f-0184-7248-8d64-3c723c523111
  [8/100] OK: Control → 018d937f-4614-7311-8f5e-54720a2e73c2
  [9/100] OK: Spec Ops: The Line → 018d937e-f9cd-7155-9615-a06d7a4e3b81
  [10/100] OK: Call of Duty: Black Ops II → 018d9571-ca0b-7131-bb1e-05633a089597
  [11/100] OK: Half-Life 2: Episode One → 018d937f-088b-7364-941d-be6b308787b1
  [12/100] OK: Team Fortress 2 → 018d937e-fde4-72ff-a7af-45e4955a8dd6
  [13/100] OK: Cuphead → 018d937e-ffba-7200-8bc4-99eccd424fa1
  [14/100] OK: Fallout 2 → 018d937f-039b-724c-b8fa-1766fbdf4ea9
  [15/100] OK: Metro 2033 → 018d937f-09a3-71c9-a2ee-f00c04acf2ae
  [16/100] OK: Death Stranding → 018d937f-3a88-733c-9dca-155ae7c71892
  [17/100] OK: The Walking Dead: Season Two → 018d937e-ffb9-707b-a6dd-86c93c60b01f
  [18/100] OK: Far Cry 5 → 018d937e-ff81-721c-b0a9-797caababfd7
  [19/100] OK: The Elder Scrolls III: Morrowind → 018d937e-f4b1-72a4-8b98-1b65a43ec5bb
  [20/100] OK: Titanfall 2 → 018d937f-267f-730f-bba4-2d6b52801740
  [21/100] OK: Super Meat Boy → 018d937f-22a3-73c2-b90f-0ea5c89c6ab9
  [22/100] OK: Dark Souls II → 018d937f-122f-73c1-a7bc-2d10bdb92d90
  [23/100] OK: Call of Duty → 018d956f-254c-711e-a867-e0fe52ffdb58
  [24/100] OK: Halo 3 → 018d937f-0e31-7291-90f7-030a63192a6f
  [25/100] OK: Outer Wilds → 018d937f-09dd-729b-88aa-5496f800b3bd
  [26/100] OK: Assassin's Creed Syndicate → 018d937e-fdd8-73fc-b6f2-669d6969f960
  [27/100] OK: Star Wars: Knights of the Old Republic II - The Sith Lords → 018d937f-0388-7245-8002-506c29eecbe9
  [28/100] OK: Batman: Arkham Origins → 018d937f-1161-71bd-a3ba-b5f30a4b963b
  [29/100] OK: Resident Evil 5 → 018d937e-feb8-71a3-8819-21b3f9d400b8
  [30/100] OK: Crysis → 018d937f-0c8d-733a-b1be-779c24276b22
  [31/100] OK: Brothers: A Tale of Two Sons → 018d937f-1225-735c-8589-9516bcc67da2
  [32/100] OK: A Plague Tale: Innocence → 018d937f-2e9a-70fc-9c2e-565a87c8917b
  [33/100] OK: Dishonored 2 → 018d937f-2133-7352-904c-8ee0741c3547
  [34/100] OK: Clair Obscur: Expedition 33 → 018ffe0d-15a7-7247-bb3c-4e5e1980561f
  [35/100] OK: The Last of Us Part I → 018d937f-679e-7276-b6f1-e59da609dd4b
  [36/100] OK: Prince of Persia: The Sands of Time → 018d937f-2d6a-7013-adfa-096404f6d812
  [37/100] OK: Dota 2 → 018d937f-19a5-7057-bb6d-314d586e6dbc
  [38/100] OK: Bastion → 018d937f-05be-7337-8877-c43351e767cb
  [39/100] OK: Counter-Strike → 018d937e-ffaf-736e-9842-0215cb593b35
  [40/100] OK: Left 4 Dead → 018d937f-27e3-71d8-bdef-4a8f482e6bb7
  [41/100] OK: Beyond: Two Souls → 018d937e-f04c-70ce-b011-e610ea57d321
  [42/100] OK: Saints Row: The Third → 018d937f-09a3-71c9-a2ee-f00c0abe998c
  [43/100] OK: Watch Dogs 2 → 018d937e-ff88-70fb-8ce4-9bda48f3048d
  [44/100] OK: Metro: Last Light → 018d937e-fa3b-7247-abc8-fce36e7fd598
  [45/100] OK: Doom Eternal → 018d937f-08a6-7233-9599-69a9ea886bd9
  [46/100] OK: Star Wars: Battlefront II → 018d956f-3d43-723c-a912-196164e7cf57
  [47/100] OK: Call of Duty: Ghosts → 018d937f-192f-72c0-a5dc-81dce349ed7b
  [48/100] OK: Little Nightmares → 018d937f-0c86-70e9-9298-ddf197875e33
  [49/100] OK: Papers, Please → 018d937f-1b83-720e-b01b-745a61d426d8
  [50/100] OK: Alien: Isolation → 018d937e-ff11-7011-8841-547a2015c0f1
  [51/100] OK: Outlast → 018d937f-0de8-7372-aa7a-fc902b95be0c
  [52/100] OK: Cities: Skylines → 018d937e-ff65-73f8-8d14-410ce85fa304
  [53/100] OK: Stray → 018d937f-194c-7075-b7c9-a3c1fd30c467
  [54/100] OK: Dragon Age II → 018d937f-60f2-71ce-95d8-bbc09d1b46ab
  [55/100] OK: Prey → 018d937f-00cb-710a-9a4c-f7c1c558b97d
  [56/100] OK: Hitman: Absolution → 018d937e-ff7d-72cb-a737-8c4850fe85a2
  [57/100] OK: Halo: Reach → 018d937f-3aa4-70ce-a7f8-f766d6f6a9c1
  [58/100] OK: Shadow of the Tomb Raider → 018d937f-3a11-70d1-81cd-cac58ba1e391
  [59/100] OK: Soma → 018d937e-fd30-70ab-baba-665d4b6c0baf
  [60/100] OK: Sleeping Dogs → 018d937e-f984-725f-9f1b-8e1f731990a3
  [61/100] OK: Rayman Legends → 018d937e-fd30-70ab-baba-665d4b44339a
  [62/100] OK: Apex Legends → 018d937f-0ddf-7119-9337-aa96d8a36d39
  [63/100] OK: Persona 5 Royal → 018d937f-4adb-73a6-a9e5-94ff62f6265b
  [64/100] OK: Fallout: A Post Nuclear Role Playing Game → 018d937f-2237-7301-a0d8-7074fb89a8d0
  [65/100] OK: The Sims 4 → 018d937e-f8b9-702f-ab65-2b3ba5da16e6
  [66/100] OK: Battlefield: Bad Company 2 → 018d937e-fdac-7257-b2e3-5676e6d89c37
  [67/100] OK: Metro Exodus → 018d937f-1e66-7184-b1d7-1634c8fc9df4
  [68/100] OK: A Way Out → 018d937f-2077-7336-b125-3cd9641887eb
  [69/100] OK: The Sims 3 → 018d937e-f8b6-7306-b06c-689a8866f52a
  [70/100] OK: The Outer Worlds → 018d937f-1304-7116-8fdf-d7aacd34cfb9
  [71/100] OK: Sonic the Hedgehog → 018d937f-061c-7307-bdaa-f84aae501734
  [72/100] OK: Wolfenstein II: The New Colossus → 018d937f-1d1e-7172-a80b-3b57776007c8
  [73/100] OK: Dead Cells → 018d937f-2b4b-72f9-ab75-bc33784a295d
  [74/100] OK: Destiny 2 → 018d937f-1609-7272-a6c7-61100a9fd54c
  [75/100] OK: Hogwarts Legacy → 018d937f-6144-7057-ad1c-0e99a3a71797
  [76/100] OK: Resident Evil 4 → 018d937f-74c1-708e-8193-97dfbe6a98fe
  [77/100] OK: Sonic the Hedgehog 2 → 018d937e-ea44-71c8-bd9f-9842258f5c18
  [78/100] OK: Sid Meier's Civilization VI → 018d937e-f81a-7288-868c-49236397885a
  [79/100] OK: Call of Duty: Advanced Warfare → 018d937f-0c3d-7270-a624-22a0e2b2734c
  [80/100] OK: Vampire: The Masquerade - Bloodlines → 018d937f-1cfa-70aa-a062-8eee73661b8e
  [81/100] OK: Braid → 018d937f-0651-7276-9c5d-9628dcc6b352
  [82/100] OK: PUBG: Battlegrounds → 018d937f-57ce-723f-b7e7-7c7b5df93471
  [83/100] OK: No Man's Sky → 018d937f-15f9-7056-8edf-2e8fa4b8f357
  [84/100] OK: Call of Duty: WWII → 018d937f-0e1e-70f5-85f9-797eb8bb0d39
  [85/100] OK: Days Gone → 018d937f-4ca6-7067-aee5-c1ed89a268f4
  [86/100] OK: Resident Evil 2 → 01926c93-cf48-73a8-9733-2768b5558c04
  [87/100] OK: The Witcher 3: Wild Hunt - Game of the Year Edition → 018d937f-24aa-703a-9c4a-a4d37a72c474
  [88/100] OK: F.E.A.R. → 018d937f-2e52-73c1-b717-f9bfd31f41da
  [89/100] OK: Call of Duty: Black Ops III → 018d937e-ea27-712b-b589-66a2265d60d9
  [90/100] OK: Subnautica → 018d937f-27b1-70c3-8978-7c37211c3dfa
  [91/100] OK: Assassin's Creed Rogue → 018d937e-f9bd-732a-8129-55703fce0e08
  [92/100] OK: Tales from the Borderlands → 018d937f-348e-7147-b777-b7754abcc2e7
  [93/100] OK: Resident Evil 3 → 018d937f-7829-7173-8d70-703fec94e4d6
  [94/100] OK: Monster Hunter: World → 018d937e-fd94-7238-a99b-14457502670c
  [95/100] OK: Saints Row IV → 018d937f-3e06-72b3-9d2e-b0b028dcb3df
  [96/100] OK: Among Us → 018d937f-32ad-726b-b62a-3d4a7df71044
  [97/100] OK: Deus Ex: Mankind Divided → 018d937f-07c2-7077-bebc-928c09f137d8
  [98/100] OK: Hitman → 018d937f-222d-7300-b046-874f2a8d710f
  [99/100] OK: Mad Max → 018d937f-105d-72c2-ac96-b538ae0967f1
  [100/100] OK: Borderlands 3 → 018d937f-21da-71a5-b774-323d7a867ff8
100 juegos a vincular
  [1/100] no encontrado: Counter-Strike: Global Offensive
  [2/100] OK: Ori and the Will of the Wisps → 018d937f-3cc5-7116-b8e1-06ca7dd2e7ca
  [3/100] OK: XCOM: Enemy Unknown → 018d937e-fd5e-7114-937e-5357a75217fc
  [4/100] OK: Fall Guys → 018d937f-4640-728f-9dee-ff5702d93303
  [5/100] OK: Far Cry 2 → 018d937f-2067-73c1-912d-8192a3f11244
  [6/100] OK: Hitman: Blood Money → 018d937e-f9c8-727a-ad7b-cb2c440e3e66
  [7/100] OK: The Witcher 3: Wild Hunt - Hearts of Stone → 018d9589-dd61-71cb-b314-c914cb0d2b0e
  [8/100] OK: Rainbow Six Siege → 018d937f-0165-7011-8fe2-f82705e769d8
  [9/100] OK: Star Wars Battlefront II → 018d937f-1b60-7380-8a75-fd184ab29229
  [10/100] OK: Grand Theft Auto 2 → 018d937f-085d-721d-a154-bd7a62a05c37
  [11/100] OK: Gone Home → 018d937f-0f8b-713e-ae8f-98f3cde0b649
  [12/100] OK: Marvel's Spider-Man: Miles Morales → 018d937f-4b30-71db-a955-18758fe9e7c5
  [13/100] OK: The Binding of Isaac: Rebirth → 018d937f-09ae-70b2-8269-996df377eeea
  [14/100] OK: SuperHot → 018d937f-1cbd-7296-bbab-6f18ea3da5ed
  [15/100] OK: Gris → 018d937f-1056-73e9-8a9a-7595ec633fe4
  [16/100] OK: Black Mesa → 018d937f-20eb-70ae-bb67-f6d04b00780d
  [17/100] OK: Resident Evil 6 → 018d937e-fd75-7351-be7d-a0be822b98a1
  [18/100] OK: Far Cry → 018d937f-1907-72cf-8690-c574012a635d
  [19/100] OK: Dark Souls: Remastered → 018d937f-03e5-729e-aece-46616a6ea2eb
  [20/100] OK: Halo 4 → 018d937f-2bee-71d8-97b2-18b2eb954af6
  [21/100] OK: Devil May Cry 5 → 018d937f-556c-700b-adaa-249a833f300c
  [22/100] OK: Counter-Strike: Source → 018d937f-1d0a-704b-ae79-598acc6c23c5
  [23/100] OK: Metal Gear Rising: Revengeance → 018d937f-1add-71a2-bfee-94605533db7a
  [24/100] OK: Amnesia: The Dark Descent → 018d937e-fd59-7327-b092-ea31b923d483
  [25/100] OK: Resident Evil Village → 018d937f-437a-728f-aa59-d868be98fb65
  [26/100] OK: Prince of Persia: Warrior Within → 018d937f-08bf-7319-a330-1d4fb2b0d954
  [27/100] OK: Doom II: Hell on Earth → 018d937f-2202-7382-b668-61c8f41016f2
  [28/100] OK: Shovel Knight → 018d937f-3ab0-72b1-9ddf-7fea5c40a018
  [29/100] OK: Doki Doki Literature Club! → 018d937f-0990-729f-99f8-08da754a7173
  [30/100] OK: The Witness → 018d937e-f4d7-7087-b8f9-3e7dcd246f09
  [31/100] OK: Slay the Spire → 018d937f-285e-7065-a58b-23400688cc12
  [32/100] OK: Warframe → 018d937f-2ec7-71f0-bfd9-403de410885d
  [33/100] OK: Life is Strange: Before the Storm → 018d937f-1198-7205-90f5-28d962d4c345
  [34/100] OK: Yakuza 0 → 018d937f-0115-7117-9e47-4b60e5e821e7
  [35/100] OK: Metal Gear Solid V: Ground Zeroes → 018d937f-07d1-7345-b35d-d1e6ae941a69
  [36/100] OK: DmC: Devil May Cry → 018d937f-0c4d-71ff-8adc-6a1bf47c362b
  [37/100] OK: Payday 2 → 018d937f-2947-726f-ab1e-7bf149096fff
  [38/100] OK: Path of Exile → 018d937e-fee4-72da-8ff3-0f7606f04b7a
  [39/100] OK: Transistor → 018d937f-11d2-70c4-9b73-0a6cf0e6f35e
  [40/100] OK: Return of the Obra Dinn → 018d937f-19bc-708a-8ae0-2eb4e68c4865
  [41/100] OK: Mortal Kombat X → 018d937f-0c3b-716c-9b8d-b420f9850264
  [42/100] OK: Tomb Raider → 018d9573-86c4-70ce-b106-a885d3eb3759
  [43/100] OK: Just Cause 2 → 018d937e-f9fc-7308-8e8c-86a79602112d
  [44/100] OK: Mafia III → 018d937f-4292-724a-a13a-1f1da1652741
  [45/100] OK: Prince of Persia: The Two Thrones → 018d937e-feee-707c-aac3-0dba9a4736db
  [46/100] OK: The Witcher 3: Wild Hunt - Blood and Wine → 018d937f-2299-7120-be99-fa7f8eeb8018
  [47/100] OK: Far Cry: Primal → 018d937e-fee0-7282-a941-79b83314440f
  [48/100] OK: Resident Evil → 018d937f-1e98-7204-9325-3e3295ce44c9
  [49/100] OK: Middle-earth: Shadow of War → 018d937e-f835-710c-b95b-928e2f1d4da8
  [50/100] OK: Abzu → 018d937f-11d2-70c4-9b73-0a6cf40fe771
  [51/100] OK: S.T.A.L.K.E.R.: Shadow of Chernobyl → 018d937f-2d2f-7172-9f8a-93ddf0e6e4f8
  [52/100] OK: To the Moon → 018d937e-f00b-7287-a64b-f3c1a6ed3275
  [53/100] OK: Return to Castle Wolfenstein → 018d937f-0fd6-71f2-84c4-3c9a13291e1e
  [54/100] OK: Darksiders → 018d937f-170b-72dd-b08f-99f8b2a0e67e
  [55/100] OK: Mafia: Definitive Edition → 018d937f-4293-7217-a8d5-41fbae8f2929
  [56/100] OK: Fez → 018d937f-2769-729b-acce-37166e1f805f
  [57/100] OK: The Talos Principle → 018d937f-00c4-71c2-bff0-aeaed5cf3f65
  [58/100] OK: Garry's Mod → 018d937f-0a0e-7329-8025-9daca67610a4
  [59/100] OK: Hotline Miami 2: Wrong Number → 018d937f-00d4-72bc-8556-90bb66448134
  [60/100] OK: Devil May Cry 4 → 018d937f-118b-73f2-a35c-c74d4eed9a2c
  [61/100] OK: Duke Nukem 3D → 018d937f-2b5f-711c-aad6-b86bf4d754dc
  [62/100] OK: Resident Evil 3: Nemesis → 019d4b8b-776f-73b2-8ce2-5782a7dffd4b
  [63/100] OK: Assassin's Creed Valhalla → 018d937f-4227-700c-9dbe-1190755ac02c
  [64/100] OK: The Evil Within → 018d937f-0e04-738c-8409-517f4a4c8ad3
  [65/100] OK: Call of Duty: Modern Warfare → 018d937f-157a-70f3-b1c8-4501029cce8f
  [66/100] OK: Divinity: Original Sin II → 018d937f-1b0a-715e-8022-4d0a6f824679
  [67/100] OK: Star Wars Battlefront → 018d937f-2d84-7127-9071-4a25f864566c
  [68/100] OK: Darkest Dungeon → 018d937f-17be-72b4-ac97-2a2712a897d9
  [69/100] OK: Kingdom Come: Deliverance → 018d937e-ffaf-736e-9842-0215c4cbf061
  [70/100] OK: Wolfenstein: The Old Blood → 018d937f-0dfc-7048-ac4a-eb1e77ade821
  [71/100] OK: Need for Speed: Most Wanted → 018d937e-f521-7381-80d7-e4aeb216f1e0
  [72/100] OK: Dark Souls II: Scholar of the First Sin → 018d937e-f4a3-71a0-bdde-24bbd5daf322
  [73/100] OK: Gothic → 018d937f-1346-7354-88bf-d51627b96285
  [74/100] OK: Hitman 2: Silent Assassin → 018d937f-09f3-70dc-894a-c9919d70e270
  [75/100] OK: Valiant Hearts: The Great War → 018d937f-07de-724b-b590-f87c5e066e53

In [6]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT 
            COUNT(*)                                    AS total,
            COUNT(itad_id_texto)                        AS vinculados,
            COUNT(*) - COUNT(itad_id_texto)             AS sin_vincular
        FROM CAT_Juego
        WHERE id_steam IS NOT NULL
    """, conn)
    display(df)

   total  vinculados  sin_vincular
0   7181        7172             9

In [7]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT juego_id, titulo, id_steam,categoria
        FROM CAT_Juego
        WHERE id_steam IS NOT NULL
          AND itad_id_texto IS NULL
    """, conn)
    display(df)

   juego_id                                 titulo  id_steam        categoria
0        73       Counter-Strike: Global Offensive   4465480  Juego principal
1      1274                       Street Fighter 6   1952120  Juego principal
2      1419                                FIFA 23   1962391  Juego principal
3      1614                                Warface   3889960  Juego principal
4      2750  Tomb Raider: Game of the Year Edition    379180           Bundle
5      3532                              SpaceChem    775011  Juego principal
6      4642            Men of War: Assault Squad 2    562040  Juego principal
7      8079             Team Fortress 2 Classified   3545060              Mod
8      9182                                 0 A.D.   2158440  Juego principal

# obtener precios

In [8]:
res = requests.get(
    f"{ITAD_BASE}/service/shops/v1",
    params={"country": "US"},
    timeout=TIMEOUT
)
print(res.status_code)
shops = res.json()
df_shops = pd.DataFrame(shops)
display(df_shops[df_shops['title'].str.contains('Steam', case=False, na=False)])

200

    id  title  deals   games                     update
28  61  Steam  23958  268319  2026-04-10T23:00:59+02:00

In [9]:
STEAM_SHOP_ID = 61

In [10]:
def fetch_historial_steam(itad_id, meses_atras=24):
    since = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=meses_atras * 30)
    
    res = requests.get(
        f"{ITAD_BASE}/games/history/v2",
        params={
            "key":   ITAD_KEY,
            "id":    itad_id,
            "shops": STEAM_SHOP_ID,
            "since": since.strftime('%Y-%m-%dT%H:%M:%SZ')
        },
        timeout=TIMEOUT
    )
    if res.status_code != 200:
        return []

    return [
        {
            "precio_base": c["deal"]["regular"]["amount"],
            "precio":      c["deal"]["price"]["amount"],
            "descuento":   c["deal"]["cut"],
            "fecha_unix":  int(datetime.datetime.fromisoformat(c["timestamp"]).timestamp())
        }
        for c in res.json()
    ]

In [11]:
def buscar_itad(titulo):
    res = requests.get(
        f"{ITAD_BASE}/games/search/v1",
        params={"key": ITAD_KEY, "title": titulo, "limit": 5},
        timeout=TIMEOUT
    )
    for r in res.json():
        print(f" {r['id']} — {r['title']}")

In [12]:
buscar_itad("resident evil 4")

 018d937f-6b99-7077-9cf6-eacfce97587f — Resident Evil 4 (2005)
 018d937f-74c1-708e-8193-97dfbe6a98fe — Resident Evil 4 (2023)
 018d937f-751c-72ae-af51-cc2ae4a8726f — Resident Evil 4 - Separate Ways
 018d937f-32cf-736d-a8fb-0e2a4b3b3d4c — Resident Evil 0 Costume Pack 4
 018d937f-6c9f-720e-85fb-da2c0428a2bb — Resident Evil 4 - The Mercenaries
 018f084f-a7d1-7026-ba37-f11927b55307 — Resident Evil 4 (2023) - Gold Edition
 018d937f-6bee-71a1-89df-c91a7026c2b4 — Resident Evil 4 Deluxe Weapon: 'Skull Shaker'
 018d937f-6bee-71a1-89df-c91a6f3c9598 — Resident Evil 4 Deluxe Weapon: 'Sentinel Nine'
 018d937f-6bee-71a1-89df-c91a6e486b15 — Resident Evil 4 Leon Accessory: 'Sunglasses (Sporty)'
 018d937f-6bee-71a1-89df-c91a6d3cc51a — Resident Evil 4 'Original Ver.' Soundtrack Swap
 018d937f-6bee-71a1-89df-c91a6d3b63ac — Resident Evil 4 Leon Costume & Filter: 'Hero'
 018d937f-6bed-737d-b6d8-9bf0b165ad50 — Resident Evil 4 Leon & Ashley Costumes: 'Casual'
 018d937f-6bed-737d-b6d8-9bf0b118196d — Resident Evil 4 Leon Costume & Filter: 'Villain'
 018d937f-6bed-737d-b6d8-9bf0b066b63b — Resident Evil 4 Treasure Map: Expansion
 018d937f-6bed-737d-b6d8-9bf0af7f6115 — Resident Evil 4 Leon & Ashley Costumes: 'Romantic'
 018d937f-6632-7297-ba07-ca331b26ebfc — Resident Evil 4 Deluxe Edition
 018d937f-716f-7110-98f1-10d510c119c1 — Resident Evil 4 Charm: 'Handgun Ammo'
 018d937f-716f-7110-98f1-10d50e883843 — Resident Evil 4 Attaché Case: 'Gold'
 018d937f-716f-7110-98f1-10d51039862e — Resident Evil 4 Charm: 'Green Herb'
 018d937f-716f-7110-98f1-10d50f560a77 — Resident Evil 4 Attaché Case: 'Classic'

In [13]:
historial = fetch_historial_steam("018d937f-74c1-708e-8193-97dfbe6a98fe", meses_atras=60)
print(f"{len(historial)} registros")
for r in historial:
    print(r)

51 registros
{'precio_base': 39.99, 'precio': 15.99, 'descuento': 60, 'fecha_unix': 1775063776}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1772129990}
{'precio_base': 39.99, 'precio': 15.99, 'descuento': 60, 'fecha_unix': 1770920579}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1767641357}
{'precio_base': 39.99, 'precio': 15.99, 'descuento': 60, 'fecha_unix': 1765477169}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1762881334}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1761758251}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1759774647}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1758647934}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1756055979}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1754932916}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1752170898}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1750977889}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1750370657}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1749144552}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1746551969}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1745428779}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1742836760}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1741799895}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1739212965}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1738002630}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1735844391}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1734027577}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1733339889}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1732742367}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1731431728}
{'precio_base': 39.99, 'precio': 19.99, 'descuento': 50, 'fecha_unix': 1730222315}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1727630324}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1726507223}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1722878463}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1721668809}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1720722872}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1719513766}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1718990303}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1717780701}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1714411006}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1713201730}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1711043151}
{'precio_base': 39.99, 'precio': 29.99, 'descuento': 25, 'fecha_unix': 1709230695}
{'precio_base': 39.99, 'precio': 39.99, 'descuento': 0, 'fecha_unix': 1707647330}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1706641773}
{'precio_base': 59.99, 'precio': 29.99, 'descuento': 50, 'fecha_unix': 1706119609}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1704403515}
{'precio_base': 59.99, 'precio': 29.99, 'descuento': 50, 'fecha_unix': 1701972810}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1701206323}
{'precio_base': 59.99, 'precio': 39.59, 'descuento': 34, 'fecha_unix': 1700602510}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1699377596}
{'precio_base': 59.99, 'precio': 39.59, 'descuento': 34, 'fecha_unix': 1698253422}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1695664583}
{'precio_base': 59.99, 'precio': 39.59, 'descuento': 34, 'fecha_unix': 1694452779}
{'precio_base': 59.99, 'precio': 59.99, 'descuento': 0, 'fecha_unix': 1666307891}

In [14]:
res = requests.post(
    f"{ITAD_BASE}/games/prices/v3",
    params={"key": ITAD_KEY, "country": "US", "shops": STEAM_SHOP_ID},
    json=["018d937f-74c1-708e-8193-97dfbe6a98fe"],
    timeout=TIMEOUT
)
print(res.status_code)
print(json.dumps(res.json(), indent=2))

200
[
  {
    "id": "018d937f-74c1-708e-8193-97dfbe6a98fe",
    "historyLow": {
      "all": {
        "amount": 9.6,
        "amountInt": 960,
        "currency": "USD"
      },
      "y1": {
        "amount": 12.9,
        "amountInt": 1290,
        "currency": "USD"
      },
      "m3": {
        "amount": 13.59,
        "amountInt": 1359,
        "currency": "USD"
      }
    },
    "deals": [
      {
        "shop": {
          "id": 61,
          "name": "Steam"
        },
        "price": {
          "amount": 15.99,
          "amountInt": 1599,
          "currency": "USD"
        },
        "regular": {
          "amount": 39.99,
          "amountInt": 3999,
          "currency": "USD"
        },
        "cut": 60,
        "voucher": null,
        "storeLow": {
          "amount": 15.99,
          "amountInt": 1599,
          "currency": "USD"
        },
        "flag": "S",
        "drm": [],
        "platforms": [
          {
            "id": 1,
            "name": "Windows"
          }
        ],
        "timestamp": "2026-04-01T19:16:16+02:00",
        "expiry": "2026-04-15T19:00:00+02:00",
        "url": "https://itad.link/018d9386-b8da-7127-8f10-5bd3628d64bf/"
      }
    ]
  }
]

In [15]:
def fetch_precio_actual(itad_id):
    res = requests.post(
        f"{ITAD_BASE}/games/prices/v3",
        params={"key": ITAD_KEY, "country": "US", "shops": STEAM_SHOP_ID},
        json=[itad_id],
        timeout=TIMEOUT
    )
    if res.status_code != 200 or not res.json():
        return None, None, None, None, None

    data  = res.json()[0]
    deals = data.get("deals", [])

    precio_actual    = deals[0]["price"]["amount"]                                          if deals else None
    descuento_actual = deals[0]["cut"]                                                      if deals else None
    expiry           = int(datetime.datetime.fromisoformat(deals[0]["expiry"]).timestamp()) if deals and deals[0].get("expiry") else None
    precio_minimo    = deals[0]["storeLow"]["amount"]                                       if deals and deals[0].get("storeLow") else None
    fecha_minimo     = int(datetime.datetime.fromisoformat(deals[0]["timestamp"]).timestamp()) if deals else None

    return precio_actual, descuento_actual, expiry, precio_minimo, fecha_minimo

In [16]:
print(fetch_precio_actual("018d937f-74c1-708e-8193-97dfbe6a98fe"))

(15.99, 60, 1776272400, 15.99, 1775063776)

In [17]:
def procesar_lote(meses_atras=12, limite=100):
    with sqlite3.connect(DB_PATH) as conn:
        pendientes = conn.execute("""
            SELECT j.itad_id_texto
            FROM CAT_Juego j
            LEFT JOIN Datos_Actuales_ITAD d ON j.itad_id_texto = d.itad_id_texto
            WHERE j.itad_id_texto IS NOT NULL
              AND d.itad_id_texto IS NULL
            LIMIT ?
        """, (limite,)).fetchall()

    if not pendientes:
        print("Sin pendientes.")
        return 0

    total = len(pendientes)
    print(f"{total} juegos a procesar")

    for i, (itad_id,) in enumerate(pendientes, 1):
        try:
            historial                                              = fetch_historial_steam(itad_id, meses_atras)
            precio_actual, descuento_actual, expiry, precio_minimo, fecha_minimo = fetch_precio_actual(itad_id)

            with sqlite3.connect(DB_PATH) as conn:
                if historial:
                    conn.executemany("""
                        INSERT OR IGNORE INTO Hist_Precios_ITAD
                        (itad_id_texto, precio_base, precio, descuento, fecha_unix)
                        VALUES (?, ?, ?, ?, ?)
                    """, [(itad_id, r["precio_base"], r["precio"], r["descuento"], r["fecha_unix"]) for r in historial])

                conn.execute("""
                    INSERT OR REPLACE INTO Datos_Actuales_ITAD
                    (itad_id_texto, precio_actual, precio_minimo, fecha_minimo,
                     descuento_actual, expiry, fecha_actualizacion)
                    VALUES (?, ?, ?, ?, ?, ?, strftime('%s','now'))
                """, (itad_id, precio_actual, precio_minimo, fecha_minimo, descuento_actual, expiry))

            print(f"  [{i}/{total}] {itad_id} — hist: {len(historial)} | actual: {precio_actual} | min: {precio_minimo}")

        except KeyboardInterrupt:
            print(f"\nInterrumpido en [{i}/{total}].")
            return i
        except Exception as e:
            print(f"  [{i}/{total}] error {itad_id}: {e}")

        time.sleep(0.5)

    return total

In [ ]:
# with sqlite3.connect(DB_PATH) as conn:
#     conn.executescript("""
#         DELETE FROM Hist_Precios_ITAD;
#         DELETE FROM Datos_Actuales_ITAD;
#     """)
# print("Tablas limpias.")

Tablas limpias.

In [ ]:
while procesar_lote(meses_atras=12, limite=100) > 0:
    time.sleep(5)
print("Todos procesados.")

100 juegos a procesar
  [1/100] 018d937f-07c2-7077-bebc-928c09f137d8 — hist: 18 | actual: 29.99 | min: 4.49
  [2/100] 018d937f-222d-7300-b046-874f2a8d710f — hist: 0 | actual: None | min: None
  [3/100] 018d937f-105d-72c2-ac96-b538ae0967f1 — hist: 13 | actual: 19.99 | min: 1.99
  [4/100] 018d937f-21da-71a5-b774-323d7a867ff8 — hist: 18 | actual: 5.99 | min: 2.99
  [5/100] 018d937f-3cc5-7116-b8e1-06ca7dd2e7ca — hist: 17 | actual: 29.99 | min: 5.99
  [6/100] 018d937e-fd5e-7114-937e-5357a75217fc — hist: 19 | actual: 14.99 | min: 1.49
  [7/100] 018d937f-4640-728f-9dee-ff5702d93303 — hist: 0 | actual: None | min: None
  [8/100] 018d937f-2067-73c1-912d-8192a3f11244 — hist: 18 | actual: 9.99 | min: 2.49
  [9/100] 018d937e-f9c8-727a-ad7b-cb2c440e3e66 — hist: 23 | actual: 9.99 | min: 0.99
  [10/100] 018d9589-dd61-71cb-b314-c914cb0d2b0e — hist: 19 | actual: 9.99 | min: 1.99
  [11/100] 018d937f-0165-7011-8fe2-f82705e769d8 — hist: 6 | actual: 0 | min: 3.99
  [12/100] 018d937f-1b60-7380-8a75-fd184ab29229 — hist: 0 | actual: None | min: None
  [13/100] 018d937f-085d-721d-a154-bd7a62a05c37 — hist: 0 | actual: None | min: None
  [14/100] 018d937f-0f8b-713e-ae8f-98f3cde0b649 — hist: 23 | actual: 14.99 | min: 1.49
  [15/100] 018d937f-4b30-71db-a955-18758fe9e7c5 — hist: 13 | actual: 49.99 | min: 19.99
  [16/100] 018d937f-09ae-70b2-8269-996df377eeea — hist: 11 | actual: 14.99 | min: 4.94
  [17/100] 018d937f-1cbd-7296-bbab-6f18ea3da5ed — hist: 20 | actual: 7.49 | min: 7.49
  [18/100] 018d937f-1056-73e9-8a9a-7595ec633fe4 — hist: 17 | actual: 14.99 | min: 1.49
  [19/100] 018d937f-20eb-70ae-bb67-f6d04b00780d — hist: 17 | actual: 19.99 | min: 1.99
  [20/100] 018d937e-fd75-7351-be7d-a0be822b98a1 — hist: 0 | actual: None | min: None
  [21/100] 018d937f-1907-72cf-8690-c574012a635d — hist: 18 | actual: 9.99 | min: 2.49
  [22/100] 018d937f-03e5-729e-aece-46616a6ea2eb — hist: 9 | actual: 39.99 | min: 19.99
  [23/100] 018d937f-2bee-71d8-97b2-18b2eb954af6 — hist: 13 | actual: 9.99 | min: 2.49
  [24/100] 018d937f-556c-700b-adaa-249a833f300c — hist: 18 | actual: 29.99 | min: 7.49
  [25/100] 018d937f-1d0a-704b-ae79-598acc6c23c5 — hist: 9 | actual: 9.99 | min: 0.99
  [26/100] 018d937f-1add-71a2-bfee-94605533db7a — hist: 3 | actual: 29.99 | min: 5.99
  [27/100] 018d937e-fd59-7327-b092-ea31b923d483 — hist: 22 | actual: 19.99 | min: 0.99
  [28/100] 018d937f-437a-728f-aa59-d868be98fb65 — hist: 18 | actual: 9.99 | min: 9.99
  [29/100] 018d937f-08bf-7319-a330-1d4fb2b0d954 — hist: 18 | actual: 9.99 | min: 1.99
  [30/100] 018d937f-2202-7382-b668-61c8f41016f2 — hist: 0 | actual: None | min: None
  [31/100] 018d937f-3ab0-72b1-9ddf-7fea5c40a018 — hist: 3 | actual: 14.99 | min: 7.49
  [32/100] 018d937f-0990-729f-99f8-08da754a7173 — hist: 1 | actual: 0 | min: None
  [33/100] 018d937e-f4d7-7087-b8f9-3e7dcd246f09 — hist: 19 | actual: 39.99 | min: 7.19
  [34/100] 018d937f-285e-7065-a58b-23400688cc12 — hist: 22 | actual: 24.99 | min: 2.49
  [35/100] 018d937f-2ec7-71f0-bfd9-403de410885d — hist: 1 | actual: 0 | min: None
  [36/100] 018d937f-1198-7205-90f5-28d962d4c345 — hist: 1 | actual: 16.99 | min: 3.39
  [37/100] 018d937f-0115-7117-9e47-4b60e5e821e7 — hist: 8 | actual: None | min: None
  [38/100] 018d937f-07d1-7345-b35d-d1e6ae941a69 — hist: 3 | actual: 19.99 | min: 1.99
  [39/100] 018d937f-0c4d-71ff-8adc-6a1bf47c362b — hist: 18 | actual: 29.99 | min: 7.49
  [40/100] 018d937f-2947-726f-ab1e-7bf149096fff — hist: 19 | actual: 9.99 | min: 0.99
  [41/100] 018d937e-fee4-72da-8ff3-0f7606f04b7a — hist: 1 | actual: 0 | min: None
  [42/100] 018d937f-11d2-70c4-9b73-0a6cf0e6f35e — hist: 9 | actual: 19.99 | min: 2.99
  [43/100] 018d937f-19bc-708a-8ae0-2eb4e68c4865 — hist: 7 | actual: 19.99 | min: 9.99
  [44/100] 018d937f-0c3b-716c-9b8d-b420f9850264 — hist: 19 | actual: 19.99 | min: 3.99
  [45/100] 018d9573-86c4-70ce-b106-a885d3eb3759 — hist: 7 | actual: 6.99 | min: 0.97
  [46/100] 018d937e-f9fc-7308-8e8c-86a79602112d — hist: 17 | actual: 14.99 | min: 1.49
  [47/100] 018d937f-4292-724a-a13a-1f1da1652741 — hist: 19 | actual: 29.99 | min: 2.99
  [48/100] 018d937e-feee-707c-aac3-0dba9a4736db — hist: 20 | actual: 9.99 | min: 1.99
  [49/100] 018d937f-2299-7120-be99-fa7f8eeb8018 — hist: 19 | actual: 19.99 | min: 3.99
  [50/100] 018d937e-fee0-7282-a941-79b83314440f — hist: 19 | actual: 29.99 | min: 2.99
  [51/100] 018d937f-1e98-7204-9325-3e3295ce44c9 — hist: 20 | actual: 4.99 | min: 4.99
  [52/100] 018d937e-f835-710c-b95b-928e2f1d4da8 — hist: 17 | actual: 49.99 | min: 2.49
  [53/100] 018d937f-11d2-70c4-9b73-0a6cf40fe771 — hist: 18 | actual: 4.99 | min: 4.99
  [54/100] 018d937f-2d2f-7172-9f8a-93ddf0e6e4f8 — hist: 1 | actual: 19.99 | min: 3.99
  [55/100] 018d937e-f00b-7287-a64b-f3c1a6ed3275 — hist: 17 | actual: 9.99 | min: 1.49
  [56/100] 018d937f-0fd6-71f2-84c4-3c9a13291e1e — hist: 15 | actual: 4.99 | min: 1.24
  [57/100] 018d937f-170b-72dd-b08f-99f8b2a0e67e — hist: 0 | actual: None | min: None
  [58/100] 018d937f-4293-7217-a8d5-41fbae8f2929 — hist: 19 | actual: 39.99 | min: 5.99
  [59/100] 018d937f-2769-729b-acce-37166e1f805f — hist: 12 | actual: 9.99 | min: 0.99
  [60/100] 018d937f-00c4-71c2-bff0-aeaed5cf3f65 — hist: 17 | actual: 29.99 | min: 2.99
  [61/100] 018d937f-0a0e-7329-8025-9daca67610a4 — hist: 18 | actual: 9.99 | min: 2.49
  [62/100] 018d937f-00d4-72bc-8556-90bb66448134 — hist: 13 | actual: 14.99 | min: 2.24
  [63/100] 018d937f-118b-73f2-a35c-c74d4eed9a2c — hist: 0 | actual: None | min: None
  [64/100] 018d937f-2b5f-711c-aad6-b86bf4d754dc — hist: 0 | actual: None | min: None
  [65/100] 019d4b8b-776f-73b2-8ce2-5782a7dffd4b — hist: 1 | actual: 4.99 | min: 4.99
  [66/100] 018d937f-4227-700c-9dbe-1190755ac02c — hist: 22 | actual: 59.99 | min: 5.99
  [67/100] 018d937f-0e04-738c-8409-517f4a4c8ad3 — hist: 17 | actual: 19.99 | min: 2.99
  [68/100] 018d937f-157a-70f3-b1c8-4501029cce8f — hist: 18 | actual: 59.99 | min: 5.99
  [69/100] 018d937f-1b0a-715e-8022-4d0a6f824679 — hist: 13 | actual: 44.99 | min: 11.24
  [70/100] 018d937f-2d84-7127-9071-4a25f864566c — hist: 0 | actual: None | min: None
  [71/100] 018d937f-17be-72b4-ac97-2a2712a897d9 — hist: 21 | actual: 3.74 | min: 1.99
  [72/100] 018d937e-ffaf-736e-9842-0215c4cbf061 — hist: 21 | actual: 29.99 | min: 2.99
  [73/100] 018d937f-0dfc-7048-ac4a-eb1e77ade821 — hist: 19 | actual: 19.99 | min: 3.99
  [74/100] 018d937e-f521-7381-80d7-e4aeb216f1e0 — hist: 19 | actual: 19.99 | min: 1.99
  [75/100] 018d937e-f4a3-71a0-bdde-24bbd5daf322 — hist: 9 | actual: 39.99 | min: 9.99
  [76/100] 018d937f-1346-7354-88bf-d51627b96285 — hist: 17 | actual: 19.99 | min: 0.99
  [77/100] 018d937f-09f3-70dc-894a-c9919d70e270 — hist: 22 | actual: 8.99 | min: 0.89
  [78/100] 018d937f-07de-724b-b590-f87c5e066e53 — hist: 19 | actual: 14.99 | min: 3.74
  [79/100] 018d937f-089f-73ea-b66e-3167274fdfe7 — hist: 15 | actual: 9.99 | min: 1.24
  [80/100] 018d937e-fd31-70ef-ab59-d59e0ca0155f — hist: 9 | actual: 5.99 | min: 1.49
  [81/100] 018d937f-0686-7187-9bf1-c96d4b6cdc4a — hist: 0 | actual: None | min: None
  [82/100] 018d937e-f8c5-7010-a344-8bec5817cdea — hist: 20 | actual: 3.99 | min: 1.99
  [83/100] 018d937e-efdc-72f3-8ab3-2dabf5d45062 — hist: 17 | actual: 19.99 | min: 3.99
  [84/100] 018d937e-fa09-732b-800b-da9ec17c3463 — hist: 26 | actual: 4.99 | min: 0.49
  [85/100] 018d937f-03dc-72d0-8283-bdeb0e98ee8c — hist: 24 | actual: 9.99 | min: 2.49
  [86/100] 018d937f-0e1c-7128-b271-f8513bf00a66 — hist: 1 | actual: 9.99 | min: 0.99
  [87/100] 018d937f-0120-723c-be2b-6037706890d2 — hist: 15 | actual: 15.99 | min: 6.39
  [88/100] 018d937e-ea63-73fc-8ae0-cb623252a68b — hist: 11 | actual: 9.99 | min: 2.49
  [89/100] 018d937f-0481-72c2-9f37-97120a68525b — hist: 17 | actual: 39.99 | min: 3.99
  [90/100] 018d937f-17f6-721f-8f97-9ca83bdd15a4 — hist: 17 | actual: 19.99 | min: 2.99
  [91/100] 018d937f-0139-72d9-b215-0d6bd7a747a3 — hist: 15 | actual: 9.99 | min: 2.49
  [92/100] 018d937f-2964-7112-80c3-a8dba9a63a9d — hist: 15 | actual: 14.99 | min: 3.74
  [93/100] 018d937f-1e67-708d-989d-b38bde2520fb — hist: 5 | actual: 19.99 | min: 15.99
  [94/100] 018d937f-1343-70f0-a3f7-3148e54c9557 — hist: 20 | actual: 2.99 | min: 2.99
  [95/100] 018d937e-f820-7061-8269-8e08a85c9911 — hist: 21 | actual: 19.99 | min: 2.99
  [96/100] 018d937f-26d6-7120-876e-6e0bdb748b70 — hist: 15 | actual: 9.99 | min: 0.89
  [97/100] 018d937f-65ec-7270-86e5-b230afacae0b — hist: 1 | actual: 0 | min: None
  [98/100] 018d937e-efe0-70c4-a142-bd045dd8c582 — hist: 0 | actual: None | min: None
  [99/100] 018d937f-1c5e-7138-848c-ba7c7a8b0b44 — hist: 13 | actual: 19.99 | min: 4.99
  [100/100] 018d937f-30a2-71a7-9634-fb31a94f9ab0 — hist: 18 | actual: 59.99 | min: 19.79
100 juegos a procesar
  [1/100] 018d937e-fef7-7274-bbce-e7d155c3d2d1 — hist: 15 | actual: 19.99 | min: 6.99
  [2/100] 018d937f-014d-73c0-8229-239746b507b2 — hist: 19 | actual: 19.99 | min: 1.99
  [3/100] 018d937f-089f-73ea-b66e-31672dad3565 — hist: 0 | actual: None | min: None
  [4/100] 018d937f-05f8-707d-bd24-938d36001e57 — hist: 18 | actual: 3.99 | min: 3.99
  [5/100] 018d937e-fd49-7027-9e59-51f9d8685cd5 — hist: 17 | actual: 29.99 | min: 2.99
  [6/100] 018d937f-15d1-7105-b09a-6ce4199e5ad8 — hist: 18 | actual: 19.99 | min: 3.99
  [7/100] 018d937f-20cc-703a-963c-8dd3f93cb88b — hist: 21 | actual: 4.99 | min: 1.99
  [8/100] 018d937f-05fe-731a-b80f-93e17fd1a2ce — hist: 1 | actual: 0 | min: None
  [9/100] 018d937f-3aa4-70ce-a7f8-f766d7b56a5a — hist: 15 | actual: 4.99 | min: 1.24
  [10/100] 018d937f-084c-705b-b1e9-14f396637088 — hist: 19 | actual: 19.99 | min: 2.49
  [11/100] 018d937f-2e92-7174-9906-4586fbe824b0 — hist: 19 | actual: 19.99 | min: 0.99
  [12/100] 018d937e-fa5d-729e-9885-a3e6d7978a85 — hist: 15 | actual: 9.99 | min: 1.24
  [13/100] 018d937f-12d3-72a3-acae-ed2350c9ce29 — hist: 20 | actual: 14.99 | min: 2.24
  [14/100] 018d937e-f55c-7305-b36f-5723071b6929 — hist: 0 | actual: None | min: None
  [15/100] 018d937f-15ba-71c9-9ddb-b2609937358f — hist: 9 | actual: 4.99 | min: 0.49
  [16/100] 018d937f-0fac-70da-a569-2ef9e5a19558 — hist: 11 | actual: 19.99 | min: 1.99
  [17/100] 018d937f-05c5-7214-8e83-90c35063ae7a — hist: 0 | actual: None | min: None
  [18/100] 018d937f-1588-7325-938c-804dd356942d — hist: 17 | actual: 2.49 | min: 2.49
  [19/100] 018d937e-fd59-7327-b092-ea31b705d7d7 — hist: 11 | actual: 19.99 | min: 1.99
  [20/100] 018d937f-1993-732b-8d28-dd8fbd7739bf — hist: 20 | actual: 14.99 | min: 3.74
  [21/100] 018d937f-1cf6-731e-a164-8875b0de891a — hist: 9 | actual: 4.99 | min: 0.49
  [22/100] 0197b3ac-94d1-7212-89a8-0e898a4552ec — hist: 7 | actual: None | min: None
  [23/100] 018d937f-1a8c-73bf-bd8c-c75f738f4452 — hist: 0 | actual: None | min: None
  [24/100] 018d937f-4610-7109-b250-072bf2e0d351 — hist: 19 | actual: 19.99 | min: 5.99
  [25/100] 018d937f-21f9-73ec-8659-31dabc9abc90 — hist: 11 | actual: 19.99 | min: 1.99
  [26/100] 018d937f-175b-7110-a8c6-7967b26caa8e — hist: 17 | actual: 39.99 | min: 7.99
  [27/100] 018d937f-51cf-71a2-8359-bde44588c59a — hist: 18 | actual: 59.99 | min: 5.99
  [28/100] 018d937e-fa60-70e4-b7e7-35c4f522ca80 — hist: 20 | actual: 14.99 | min: 3.74
  [29/100] 018d937e-f9b2-7041-8bee-10da4c1a60df — hist: 19 | actual: 14.99 | min: 2.99
  [30/100] 018d937f-00e6-73ef-a246-565a8852f91c — hist: 18 | actual: 39.99 | min: 3.99
  [31/100] 018d937f-0995-71f1-aa91-2975b7710b21 — hist: 17 | actual: 14.99 | min: 2.24
  [32/100] 018d937f-679d-712f-8751-a010d2edb5cf — hist: 18 | actual: 49.99 | min: 22.49
  [33/100] 018d937f-0399-7080-8597-46a0b7deef26 — hist: 0 | actual: None | min: None
  [34/100] 018d937f-0caf-722d-921e-b81ead53e2c3 — hist: 0 | actual: None | min: None
  [35/100] 018d937f-1174-71ec-a6fb-1da414c021cd — hist: 20 | actual: 19.99 | min: 1.99
  [36/100] 018d937f-12e1-713e-8e69-56c149cbc91d — hist: 19 | actual: 9.99 | min: 2.49
  [37/100] 018d937f-58fd-7225-ba95-dfad5f4fb3dd — hist: 17 | actual: 4.99 | min: 2.69
  [38/100] 018d937f-1f46-7086-bcd3-cd18f962376b — hist: 19 | actual: 19.99 | min: 1.19
  [39/100] 018d937f-20e1-71d4-a942-0d3711fd3ec6 — hist: 11 | actual: 9.99 | min: 2.49
  [40/100] 018d937f-19e9-7149-be8e-74557e87b546 — hist: 15 | actual: 16.99 | min: 1.69
  [41/100] 018d937f-124c-7160-9762-1144ea75581e — hist: 23 | actual: 2.99 | min: 1.49
  [42/100] 018d937f-17aa-71a9-bce1-95081f2c8fa6 — hist: 19 | actual: 29.99 | min: 2.99
  [43/100] 018d937f-3644-70b9-8ba4-77cd53f88932 — hist: 9 | actual: 14.99 | min: 1.49
  [44/100] 018d937f-700e-7161-9c8d-5423af1b7c99 — hist: 20 | actual: 14.99 | min: 11.99

Interrumpido en [45/100].
100 juegos a procesar
  [1/100] 018d937e-f8da-72fd-b64c-520e0f82391c — hist: 20 | actual: 9.99 | min: 1.99
  [2/100] 018d937f-0666-72c0-a5d2-2d6f26813db6 — hist: 18 | actual: 19.99 | min: 4.99
  [3/100] 018d937e-f86b-7210-9233-f8f9e9d21311 — hist: 18 | actual: 19.99 | min: 2.99
  [4/100] 018d937e-ea31-72ce-bf91-30dc94a27f5b — hist: 22 | actual: 29.99 | min: 2.99
  [5/100] 018d937f-6181-735a-af8a-95670cc81e27 — hist: 14 | actual: 49.99 | min: 41.99

In [21]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT *
        FROM CAT_Juego
        WHERE titulo like "%Tomb Raider%"
    """, conn)
    display(df)

,juego_id,id_igdb,id_steam,titulo,categoria,fecha_lanzamiento,resumen,historia,url_portada,puntuacion_igdb,...,hltb_completacionista,steam_price_initial,steam_price_final,steam_discount_percent,metacritic_score,recommendations_count,achievements_count,steam_languages,pc_requirements_json,itad_id_texto
0,24,1164,203160.0,Tomb Raider,Juego principal,2013-03-04,Tomb Raider explores the intense and gritty or...,he game begins with Lara setting out on her fi...,https://images.igdb.com/igdb/image/upload/t_co...,81.760627,...,None,329.00,329.00,0.0,86.0,168219.0,50.0,"Inglés<strong>*</strong>, Alemán<strong>*</str...","{""minimum"": ""<strong>Minimum:</strong><br><ul ...",018d937e-f9f4-7235-b38c-bfdcb325b577
1,74,7323,391220.0,Rise of the Tomb Raider,Juego principal,2015-11-10,Join Lara Croft on her first great tomb raidin...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,81.286752,...,None,499.00,499.00,0.0,86.0,122662.0,143.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937e-f4d8-7368-a624-4a0e38d5d2eb
2,198,37777,750920.0,Shadow of the Tomb Raider,Juego principal,2018-09-14,As Lara Croft races to save the world from a M...,In the two months since Rise of the Tomb Raide...,https://images.igdb.com/igdb/image/upload/t_co...,77.546357,...,None,669.00,669.00,0.0,77.0,69797.0,99.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-3a11-70d1-81cd-cac58ba1e391
3,305,912,224960.0,Tomb Raider,Juego principal,1996-10-24,Tomb Raider is a 3D action game developed by C...,"Lara Croft is a Tomb Raider, an archaeologist ...",https://images.igdb.com/igdb/image/upload/t_co...,80.777766,...,None,119.00,119.00,0.0,NaN,4005.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>Minimum:</strong><br><ul ...",018d9573-86c4-70ce-b106-a885d3eb3759
4,443,1156,225300.0,Tomb Raider II,Juego principal,1997-11-21,Tomb Raider II is the second game of the Tomb ...,The story begins one year after the events of ...,https://images.igdb.com/igdb/image/upload/t_co...,80.204248,...,None,119.00,119.00,0.0,NaN,2019.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>Minimum:</strong><br><ul ...",018d9573-86f5-70ae-b7a2-c82924d055c3
5,504,1161,7000.0,Tomb Raider: Legend,Juego principal,2006-04-07,Tomb Raider: Legend is the seventh major game ...,"Lara is searching for a South American relic, ...",https://images.igdb.com/igdb/image/upload/t_co...,74.816495,...,None,119.00,119.00,0.0,82.0,5203.0,0.0,"Inglés, Francés, Italiano, Alemán, Español de ...","{""minimum"": ""<strong>M\u00ednimo: </strong>Mic...",018d937f-1d16-7246-baee-aa4e147bab19
6,578,1163,8140.0,Tomb Raider: Underworld,Juego principal,2008-11-18,Tomb Raider: Underworld represents a new advan...,Continuing the events from Tomb Raider: Legend...,https://images.igdb.com/igdb/image/upload/t_co...,74.616209,...,None,149.00,149.00,0.0,80.0,5965.0,0.0,"Inglés, Francés, Italiano, Alemán, Español de ...","{""minimum"": ""M\u00ednimo<br><br> ...",018d937f-0e94-7003-b94b-805c96665bfa
7,607,1162,8000.0,Tomb Raider: Anniversary,Remake,2007-06-01,Tomb Raider: Anniversary is a remake of the or...,Lara Croft has been hired by a mysterious woma...,https://images.igdb.com/igdb/image/upload/t_co...,76.473843,...,None,149.00,149.00,0.0,83.0,6440.0,0.0,"Inglés, Francés, Alemán, Italiano, Español de ...","{""minimum"": ""<strong>M\u00ednimo: </strong>Mic...",018d937f-1974-701c-8cb8-e3f33320a0e5
8,806,1157,225320.0,Tomb Raider III: Adventures of Lara Croft,Juego principal,1998-11-20,Tomb Raider III: Adventures of Lara Croft is a...,The intrepid archaeologist Lara Croft ventures...,https://images.igdb.com/igdb/image/upload/t_co...,77.080172,...,None,119.00,119.00,0.0,NaN,1304.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>Minimum:</strong><br><ul ...",018d9573-8704-7398-b71d-3770d86747d4
9,942,19965,NaN,Tomb Raider: Definitive Edition,Remasterización,2014-01-28,Tomb Raider: Definitive Edition is a re-releas...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,83.197938,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,973,1158,224980.0,Tomb Raider: The Last Revelation,Juego principal,1999-11-24,Tomb Raider IV: The Last Revelation is the fou...,"According to Egyptian legend, Horus, son of th...",https://images.igdb.com/igdb/image/upload/t_co...,75.575178,...,None,119.00,119.00,0.0,NaN,1275.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>Minimum:</strong><br><ul ...",01927ccd-63d9-73e1-9795-9f98ad01c20d
11,1230,1159,225020.0,Tomb Raider: The Angel of Darkness,Juego principal,2003-06-20,Tomb Raider: The Angel of Darkness is the sixt...,A series of grisly murders brings Lara into co...,https://images.igdb.com/igdb/image/upload/t_co...,62.331352,...,None,119.00,119.00,0.0,NaN,1436.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",01927cd8-5f1d-70cb-9e09-78ce3f8f9bbd
12,1305,1160,225000.0,Tomb Raider: Chronicles,Juego principal,2000-11-17,Tomb Raider: Chronicles is the fifth game in t...,Tomb Raider: Chronicles opens just days after ...,https://images.igdb.com/igdb/image/upload/t_co...,68.866314,...,None,119.00,119.00,0.0,NaN,775.0,0.0,Inglés<strong>*</strong><br><strong>*</strong>...,"{""minimum"": ""<strong>Minimum:</strong><br><ul ...",01927cd8-5f36-72c4-9c1a-0b943c27aba0
13,1312,23331,NaN,Rise of the Tomb Raider: 20 Year Celebration,Bundle,2016-10-11,Rise of the Tomb Raider: 20 Year Celebration i...,"Now, after uncovering an ancient mystery, Lara...",https://images.igdb.com/igdb/image/upload/t_co...,82.073260,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2750,53818,379180.0,Tomb Raider: Game of the Year Edition,Bundle,2014-01-28,Tomb Raider is a critically acclaimed action a...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,87.310374,...,None,329.00,329.00,0.0,86.0,168219.0,50.0,"Inglés<strong>*</strong>, Alemán<strong>*</str...","{""minimum"": ""<strong>Minimum:</strong><br><ul ...",NaN
15,3193,14774,418800.0,Rise of the Tomb Raider: Baba Yaga - The Templ...,DLC,2016-01-26,Lara Croft enters the Wicked Vale and comes fa...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,76.095048,...,None,0.00,0.00,0.0,NaN,0.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937e-ff3d-7320-8422-c8aefe1ad313
16,3301,266683,2478970.0,Tomb Raider I•II•III Remastered,Bundle,2024-02-14,Tomb Raider I•II•III Remastered is a collectio...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,77.314347,...,None,334.99,334.99,0.0,NaN,6600.0,284.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-74e6-7235-a64c-16ea1e92a95d
17,4133,123051,NaN,Shadow of the Tomb Raider: Definitive Edition,Bundle,2019-11-19,In Shadow of the Tomb Raider Definitive Editio...,In the two months since Rise of the Tomb Raide...,https://images.igdb.com/igdb/image/upload/t_co...,75.884412,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5083,24890,505540.0,Rise of the Tomb Raider: Blood Ties,DLC,2016-10-11,"In the wake of her father’s death, Lara’s uncl...","Lara receives a letter from her Uncle, telling...",https://images.igdb.com/igdb/image/upload/t_co...,77.499249,...,None,0.00,0.00,0.0,NaN,482.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-0617-728a-b9c5-844425be6fda
19,6088,27555,NaN,Tomb Raider: The Lost Artifact,Expansión independiente,2000-03-01,Tomb Raider: The Lost Artifact is a mini-seque...,Lara learns of the existence of a fifth meteor...,https://images.igdb.com/igdb/image/upload/t_co...,79.669721,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,6260,319480,2525380.0,Tomb Raider IV•V•VI Remastered,Bundle,2025-02-14,Remastered collection of the Darkness Trilogy ...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,79.915924,...,None,334.99,334.99,0.0,NaN,1383.0,168.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",01927baa-a0bc-71ae-8366-d6b4c4dc38f7
21,6430,27554,NaN,Tomb Raider II: Gold,Juego ampliado,1999-06-04,Tomb Raider II: Gold is an expanded version of...,The story involves Lara Croft coming across so...,https://images.igdb.com/igdb/image/upload/t_co...,76.471233,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,7441,266698,NaN,Tomb Raider II,Remasterización,2024-02-14,"A remaster of the original Tomb Raider II, inc...",Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,80.096624,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,7442,266697,NaN,Tomb Raider,Remasterización,2024-02-14,"A remaster of the original Tomb Raider, includ...",Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,77.278908,...,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,7728,25219,418810.0,Rise of the Tomb Raider: Cold Darkness Awakened,DLC,2016-03-29,Cold Darkness Awakened is DLC for Rise of the ...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,60.106850,...,None,0.00,0.00,0.0,NaN,261.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-0173-7071-b6b8-5bd4b65e88ea
25,8133,110844,849306.0,Shadow of the Tomb Raider: The Forge,DLC,2018-10-10,"In her DLC debut, Lara must brave the lava-flo...",Lara Croft overhears Pilar and Vancho arguing ...,https://images.igdb.com/igdb/image/upload/t_co...,68.857037,...,None,0.00,0.00,0.0,NaN,213.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-2d7b-7286-8222-8b6ba8e45943
26,8776,115200,849309.0,Shadow of the Tomb Raider: The Price of Survival,DLC,2019-02-12,Return to the lush world of Shadow of the Tomb...,Q'orianka had stolen the cypher wheel of Amaru...,https://images.igdb.com/igdb/image/upload/t_co...,69.915831,...,None,0.00,0.00,0.0,NaN,0.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-309b-7383-bdfd-4f95a6acffd7
27,8779,113988,849307.0,Shadow of the Tomb Raider: The Pillar,DLC,2018-12-17,"In “The Pillar,” players will venture into the...",Lara Croft stumbled upon Q'orianka and Kumya a...,https://images.igdb.com/igdb/image/upload/t_co...,69.698881,...,None,0.00,0.00,0.0,NaN,137.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-1e9b-7219-a6ce-7a5a24459afc
28,9468,144991,208812.0,Tomb Raider: Tomb of the Lost Adventurer,DLC,2013-03-26,An optional challenge tomb DLC where Lara inve...,Sin datos,https://images.igdb.com/igdb/image/upload/t_co...,54.796163,...,None,0.00,0.00,0.0,NaN,547.0,0.0,"Inglés<strong>*</strong>, Alemán<strong>*</str...","{""minimum"": ""<strong>Minimum:</strong><br><ul ...",018d937f-30d4-716a-bc5f-a79da1a26c67
29,9600,116800,849311.0,Shadow of the Tomb Raider: The Grand Caiman,DLC,2019-03-29,"In Shadow of the Tomb Raider’s new DLC, a fero...",Lara Croft reunited with Jonah Maiava in Missi...,https://images.igdb.com/igdb/image/upload/t_co...,69.534582,...,None,0.00,0.00,0.0,NaN,110.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-19b9-719e-a37d-771cbe8fcadd
30,9610,113987,849308.0,Shadow of the Tomb Raider: The Nightmare,DLC,2019-01-22,"Journey through “The Nightmare,” as Lara Croft...",Lara Croft walks in on Uchu and Jonah Maiava s...,https://images.igdb.com/igdb/image/upload/t_co...,42.239852,...,None,0.00,0.00,0.0,NaN,0.0,0.0,"Inglés<strong>*</strong>, Francés<strong>*</st...","{""minimum"": ""<strong>M\u00ednimo:</strong><br>...",018d937f-17f2-7364-ad08-5eed7aa3ba48

In [13]:
def preparar_tablas_itad():
    conn = sqlite3.connect(DB_PATH)
    try:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS CAT_ITAD_Juego (
                itad_id_texto TEXT PRIMARY KEY,
                itad_titulo TEXT
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS REL_Juego_ITAD (
                juego_id INTEGER,
                itad_id_texto TEXT,
                PRIMARY KEY (juego_id, itad_id_texto),
                FOREIGN KEY (juego_id) REFERENCES CAT_Juego(juego_id),
                FOREIGN KEY (itad_id_texto) REFERENCES CAT_ITAD_Juego(itad_id_texto)
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS CAT_Tienda (
                id_tienda INTEGER PRIMARY KEY,
                nombre TEXT
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS Hist_Precios_ITAD (
                itad_id_texto TEXT,
                id_tienda INTEGER,
                precio REAL,
                corte_descuento INTEGER,
                fecha_unix INTEGER,
                PRIMARY KEY (itad_id_texto, id_tienda, fecha_unix)
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS Datos_Actuales_ITAD (
                itad_id_texto TEXT PRIMARY KEY,
                precio_actual REAL,
                tienda_actual INTEGER,
                precio_minimo REAL,
                tienda_minimo INTEGER,
                fecha_minimo INTEGER,
                en_bundle INTEGER DEFAULT 0,
                fecha_actualizacion INTEGER
            )
        """)
        conn.commit()
        print('Tablas listas.')
    finally:
        conn.close()

In [14]:
preparar_tablas_itad()

Tablas listas.

In [15]:
def buscar_ids_itad(limite=50):
    conn = sqlite3.connect(DB_PATH)
    try:
        juegos = conn.execute("""
            SELECT j.juego_id, j.titulo
            FROM CAT_Juego j
            LEFT JOIN REL_Juego_ITAD r ON j.juego_id = r.juego_id
            WHERE j.id_steam IS NOT NULL
              AND r.itad_id_texto IS NULL
              AND j.categoria = 0
            LIMIT ?
        """, (limite,)).fetchall()
    finally:
        conn.close()

    if not juegos:
        print('No hay más juegos por vincular.')
        return

    print(f'{len(juegos)} juegos a vincular')

    for juego_id, titulo in juegos:
        try:
            res = requests.get(
                'https://api.isthereanydeal.com/games/search/v1',
                params={'key': ITAD_KEY, 'title': titulo, 'limit': 1},
                timeout=10
            )

            if res.status_code == 200:
                data = res.json()
                if data:
                    itad_id = data[0].get('id')
                    if itad_id:
                        conn = sqlite3.connect(DB_PATH)
                        try:
                            cursor = conn.cursor()
                            cursor.execute(
                                'INSERT OR IGNORE INTO CAT_ITAD_Juego (itad_id_texto, itad_titulo) VALUES (?, ?)',
                                (itad_id, titulo)
                            )
                            cursor.execute(
                                'INSERT OR IGNORE INTO REL_Juego_ITAD (juego_id, itad_id_texto) VALUES (?, ?)',
                                (juego_id, itad_id)
                            )
                            conn.commit()
                            print(f'  OK: {titulo} -> {itad_id}')
                        finally:
                            conn.close()
                    else:
                        print(f'  sin ID: {titulo}')
                else:
                    print(f'  no encontrado: {titulo}')

            elif res.status_code == 401:
                print('  Error 401 - revisar API key')
                break
            elif res.status_code == 429:
                print('  Rate limit - esperando 20s')
                time.sleep(20)
                continue

        except Exception as e:
            print(f'  Error con {titulo}: {e}')

        time.sleep(1)

In [ ]:
#Prueba version 6 de la funcion
#buscar_ids_itad(limite=10)

In [ ]:
# Loop completo hasta obtenrlos a  todos
while True:
    conn = sqlite3.connect(DB_PATH)
    try:
        pendientes = conn.execute("""
            SELECT COUNT(*)
            FROM CAT_Juego j
            LEFT JOIN REL_Juego_ITAD r ON j.juego_id = r.juego_id
            WHERE j.id_steam IS NOT NULL
              AND r.itad_id_texto IS NULL
              AND j.categoria = 0
        """).fetchone()[0]
    finally:
        conn.close()

    if pendientes == 0:
        print('Todos los juegos vinculados.')
        break

    print(f'Faltan {pendientes} juegos')
    buscar_ids_itad(limite=100)
    print('Pausa')
    time.sleep(30)

Todos los juegos vinculados.

In [ ]:
#historial de precios desde una fecha
def _fetch_historial(itad_id, since_iso):
    res = requests.get(
        f'{ITAD_BASE}/games/history/v2',
        params={'key': ITAD_KEY, 'id': itad_id, 'country': 'MX', 'since': since_iso},
        timeout=TIMEOUT
    )
    return res.json() if res.status_code == 200 else []

#encontrar le minimo
def _fetch_low(itad_id):
    res = requests.post(
        f'{ITAD_BASE}/games/historylow/v1?key={ITAD_KEY}&country=MX',
        json=[itad_id], timeout=TIMEOUT
    )
    if res.status_code == 200 and res.json():
        low = res.json()[0].get('low')
        if low:
            ts = int(datetime.datetime.fromisoformat(low['timestamp']).timestamp()) if low.get('timestamp') else None
            return low.get('price', {}).get('amount'), low.get('shop', {}).get('id'), ts
    return None, None, None

#precio actual en tienda mas barata
def _fetch_precio_actual(itad_id):
    res = requests.post(
        f'{ITAD_BASE}/games/prices/v2?key={ITAD_KEY}&country=MX',
        json=[itad_id], timeout=TIMEOUT
    )
    if res.status_code == 200 and res.json():
        deals = res.json()[0].get('deals')
        if deals:
            return deals[0]['price']['amount'], deals[0]['shop']['id']
    return None, None

#si esta en budle el juego
#PArece que la API no funciona bien para este ya que da vacios.
def _fetch_bundle(itad_id):
    res = requests.post(
        f'{ITAD_BASE}/games/bundles/v2?key={ITAD_KEY}',
        json=[itad_id], timeout=TIMEOUT
    )
    if res.status_code == 200:
        data = res.json()
        if data and isinstance(data[0].get('bundles'), list):
            return 1 if len(data[0]['bundles']) > 0 else 0
    return 0

#usar hilos porque tarda mucho este proceso en las primeras versiones
def _procesar_juego_itad(itad_id, since_iso):
    with ThreadPoolExecutor(max_workers=4) as ex:
        fut_hist  = ex.submit(_fetch_historial, itad_id, since_iso)
        fut_low = ex.submit(_fetch_low, itad_id)
        fut_actual = ex.submit(_fetch_precio_actual, itad_id)
        fut_bundle = ex.submit(_fetch_bundle, itad_id)

        historial = fut_hist.result()
        precio_min, tienda_min, fecha_min  = fut_low.result()
        precio_act, tienda_act  = fut_actual.result()
        en_bundle = fut_bundle.result()

    return historial, precio_min, tienda_min, fecha_min, precio_act, tienda_act, en_bundle

In [ ]:
#descaragr el historial de juegos que no se aun procesado, es mejor limpiar la tabla y volver a correr
# meses_atras: cuántos meses hacia atrás pedir el historial de precios.
def procesar_lote_itad(meses_atras=1, limite_juegos=10):
    
    conn = sqlite3.connect(DB_PATH)
    conn.execute('PRAGMA journal_mode=WAL')
    conn.execute('PRAGMA synchronous=NORMAL')
    cursor = conn.cursor()

    try:
        # Solo toma juegos que aún no tienen entrada en Datos_Actuales_ITAD
        cursor.execute("""
            SELECT r.itad_id_texto
            FROM REL_Juego_ITAD r
            LEFT JOIN Datos_Actuales_ITAD d ON r.itad_id_texto = d.itad_id_texto
            WHERE d.itad_id_texto IS NULL
            LIMIT ?
        """, (limite_juegos,))

        juegos = [row[0] for row in cursor.fetchall()]

        if not juegos:
            print('Sin juegos pendientes.')
            return False

        print(f'{len(juegos)} juegos a procesar')

        fecha_dt  = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=meses_atras * 30)
        since_iso = fecha_dt.strftime('%Y-%m-%dT%H:%M:%SZ')

        for itad_id in juegos:
            print(f'\n[{itad_id}]')
            try:
                historial, precio_min, tienda_min, fecha_min, precio_act, tienda_act, en_bundle = \
                    _procesar_juego_itad(itad_id, since_iso)

                # Insertar tiendas nuevas encontradas en el historial
                tiendas_nuevas = {
                    (c['shop']['id'], c['shop'].get('name', 'Desconocida'))
                    for c in historial
                    if c.get('shop', {}).get('id')
                }
                if tiendas_nuevas:
                    cursor.executemany(
                        'INSERT OR IGNORE INTO CAT_Tienda (id_tienda, nombre) VALUES (?, ?)',
                        tiendas_nuevas
                    )

                hist_rows = []
                for cambio in historial:
                    t_id      = cambio.get('shop', {}).get('id')
                    deal      = cambio.get('deal', {})
                    precio    = deal.get('price', {}).get('amount')
                    cut       = deal.get('cut', 0)
                    fecha_str = cambio.get('timestamp')
                    if t_id and precio and fecha_str:
                        ts = int(datetime.datetime.fromisoformat(fecha_str).timestamp())
                        hist_rows.append((itad_id, t_id, precio, cut, ts))

                if hist_rows:
                    cursor.executemany("""
                        INSERT OR IGNORE INTO Hist_Precios_ITAD
                        (itad_id_texto, id_tienda, precio, corte_descuento, fecha_unix)
                        VALUES (?, ?, ?, ?, ?)
                    """, hist_rows)

                print(f'  historial: {len(hist_rows)} registros')
                print(f'  precio actual: {precio_act} | mínimo: {precio_min} | bundle: {en_bundle}')

                cursor.execute("""
                    INSERT OR REPLACE INTO Datos_Actuales_ITAD
                    (itad_id_texto, precio_actual, tienda_actual, precio_minimo,
                     tienda_minimo, fecha_minimo, en_bundle, fecha_actualizacion)
                    VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%s','now'))
                """, (itad_id, precio_act, tienda_act, precio_min, tienda_min, fecha_min, en_bundle))

                conn.commit()

            except Exception as e:
                print(f'  error en {itad_id}: {e}')
                conn.rollback()

            time.sleep(0.5)

        return True

    finally:
        conn.close()
        print('Conexión cerrada.')

In [21]:
while True:
    continuar = procesar_lote_itad(meses_atras=10, limite_juegos=200)
    if not continuar:
        break
    print('Pausa')
    time.sleep(5)

200 juegos a procesar

[018d937f-3a3b-7210-bd2d-0d1dfb1d84c0]
  historial: 356 registros
  precio actual: 14.99 | mínimo: 12.29 | bundle: 0

[018d937f-4964-7357-a557-f04dac608915]
  historial: 291 registros
  precio actual: 19.99 | mínimo: 6.83 | bundle: 0

[018d937f-012f-73b8-ab2c-898516969e6a]
  historial: 11 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937e-f877-71b3-aba5-8ff11818cd0b]
  historial: 285 registros
  precio actual: 2.99 | mínimo: 2.98 | bundle: 0

[018d937f-3497-71d8-91b5-442e6b36f0cd]
  historial: 162 registros
  precio actual: 4.99 | mínimo: 2.15 | bundle: 0

[018d937f-59ac-7213-8030-15ae80b3b930]
  historial: 0 registros
  precio actual: None | mínimo: None | bundle: 0

[018d937f-012f-73b8-ab2c-898516969e6a]
  historial: 11 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937f-4d3f-72ee-b598-97cbfa030c47]
  historial: 39 registros
  precio actual: None | mínimo: 3.74 | bundle: 0

[018d937e-f877-71b3-aba5-8ff11818cd0b]
  historial: 285 registros
  precio actual: 2.99 | mínimo: 2.98 | bundle: 0

[018d937f-4b67-7020-aac6-246767f92aa6]
  historial: 49 registros
  precio actual: 5.99 | mínimo: 4.79 | bundle: 0

[018d937f-3a3b-7210-bd2d-0d1dfb1d84c0]
  historial: 356 registros
  precio actual: 14.99 | mínimo: 12.29 | bundle: 0

[018d937f-0896-71b1-94d9-82725d1e320a]
  historial: 129 registros
  precio actual: 4.99 | mínimo: 0.99 | bundle: 0

[018d937f-3fae-7359-a783-f1a761a7c451]
  historial: 1 registros
  precio actual: None | mínimo: 9.6 | bundle: 0

[018d937e-e9db-717a-baeb-62a6513d146c]
  historial: 201 registros
  precio actual: 4.99 | mínimo: 2.5 | bundle: 0

[018d937f-1ae9-734c-ba47-bd357cf07edd]
  historial: 27 registros
  precio actual: 7.49 | mínimo: 5.09 | bundle: 0

[018d937f-590c-728b-ac35-38bcff85f086]
  historial: 135 registros
  precio actual: 44.99 | mínimo: 29.95 | bundle: 0

[018d937f-6136-71e4-a7d4-088a2e8f58ad]
  historial: 240 registros
  precio actual: 23.99 | mínimo: 10.37 | bundle: 0

[018d937e-fce8-716b-97f3-6a41f82bb9e7]
  historial: 116 registros
  precio actual: 17.48 | mínimo: 1.99 | bundle: 0

[018d937f-209c-7223-8ead-671a11f25e7e]
  historial: 145 registros
  precio actual: 52.75 | mínimo: 5.99 | bundle: 0

[018d937e-f96f-71e5-aa80-352cbee965b9]
  historial: 103 registros
  precio actual: 8.69 | mínimo: 1.7 | bundle: 0

[018d937e-efe4-70f0-920b-130e6f0c9d13]
  historial: 21 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937e-f48c-7289-8516-c7c5b2e12eba]
  historial: 290 registros
  precio actual: 2.54 | mínimo: 2.54 | bundle: 0

[018d937f-03cf-7371-b83b-3c48b18b76aa]
  historial: 0 registros
  precio actual: None | mínimo: 0.01 | bundle: 0

[018d937f-4e56-7230-a3ca-8f33a69b08de]
  historial: 41 registros
  precio actual: None | mínimo: 4.49 | bundle: 0

[018d937f-7462-73e3-96df-a80b747306b1]
  historial: 28 registros
  precio actual: None | mínimo: 4.99 | bundle: 0

[018d937e-f040-72b6-a69f-f41a0d9b16f6]
  historial: 120 registros
  precio actual: 35.99 | mínimo: 7.5 | bundle: 0

[018d937f-23f0-711e-ad7c-2cc0829d75f9]
  historial: 196 registros
  precio actual: 6.59 | mínimo: 2.91 | bundle: 0

[018d937f-1624-7008-a279-b8bfb6e55610]
  historial: 66 registros
  precio actual: 17.19 | mínimo: 1.98 | bundle: 0

[018d937e-f835-710c-b95b-928e277b187e]
  historial: 25 registros
  precio actual: None | mínimo: 7.49 | bundle: 0

[018d937f-0e82-70e5-ac00-0d05a4abc342]
  historial: 154 registros
  precio actual: 4.99 | mínimo: 3.64 | bundle: 0

[018d937e-f05c-7388-88ac-876eacf2e2fd]
  historial: 394 registros
  precio actual: 1.41 | mínimo: 1.04 | bundle: 0

[018d937f-2bba-710d-aa7f-64f220f04817]
  historial: 134 registros
  precio actual: 7.99 | mínimo: 4.23 | bundle: 0

[018d937f-33f0-7200-80fc-87f769196c84]
  historial: 21 registros
  precio actual: None | mínimo: 6.24 | bundle: 0

[018d937f-164a-71af-aabe-21230f3f3f4e]
  historial: 48 registros
  precio actual: 2.49 | mínimo: 0.99 | bundle: 0

[018d937e-ea32-7036-ad1c-5f8fb76a7583]
  historial: 37 registros
  precio actual: 1.24 | mínimo: 0.99 | bundle: 0

[01965e11-4451-728c-9e90-89e3d49f5868]
  historial: 100 registros
  precio actual: 3.74 | mínimo: 2.17 | bundle: 0

[018d937f-2997-7131-b8b9-7c8af4825fa8]
  historial: 62 registros
  precio actual: 20.99 | mínimo: 20.99 | bundle: 0

[018d937f-4292-724a-a13a-1f1da1e0ad6c]
  historial: 326 registros
  precio actual: 5.99 | mínimo: 3.75 | bundle: 0

[018d937f-2ee8-7008-bda8-5bc6436d8ae3]
  historial: 43 registros
  precio actual: 33.99 | mínimo: 13.99 | bundle: 0

[018d937f-1919-732b-82d4-9af60320b548]
  historial: 198 registros
  precio actual: 4.99 | mínimo: 2.48 | bundle: 0

[018d937f-0e0c-70be-91d5-75e399e6b4e3]
  historial: 240 registros
  precio actual: 3.36 | mínimo: 1.99 | bundle: 0

[018d937e-f856-715d-b4d3-7bc2706ddf8b]
  historial: 399 registros
  precio actual: 2.49 | mínimo: 1 | bundle: 0

[018d937f-1382-7004-b65b-e6adfce11377]
  historial: 47 registros
  precio actual: 4.99 | mínimo: 1.99 | bundle: 0

[018d9584-24d6-7010-b82b-df1f0b154cc7]
  historial: 26 registros
  precio actual: None | mínimo: 44.99 | bundle: 0

[018d937f-0a89-7069-a869-1ade408b2d54]
  historial: 0 registros
  precio actual: None | mínimo: 3.99 | bundle: 0

[018d937e-f524-7384-a34a-0a765b70ff42]
  historial: 48 registros
  precio actual: None | mínimo: 1.75 | bundle: 0

[018d937f-6b99-7077-9cf6-eacfce97587f]
  historial: 367 registros
  precio actual: 4.9 | mínimo: 3.35 | bundle: 0

[018d937f-0664-717c-8323-a3569e850699]
  historial: 346 registros
  precio actual: 3.96 | mínimo: 2.76 | bundle: 0

[018d9571-ca0b-7131-bb1e-05633a089597]
  historial: 28 registros
  precio actual: None | mínimo: 12.88 | bundle: 0

[018d937f-5599-70de-b7b0-96f7e67684ff]
  historial: 10 registros
  precio actual: None | mínimo: 26.99 | bundle: 0

[018d937f-11e6-715a-a82c-205cfda90ddd]
  historial: 192 registros
  precio actual: 4.99 | mínimo: 3.4 | bundle: 0

[018d937f-1991-707d-9471-9514de905e38]
  historial: 183 registros
  precio actual: 1.99 | mínimo: 0.75 | bundle: 0

[018d937f-0085-7156-93a8-5a7c9a7854cf]
  historial: 154 registros
  precio actual: 5.99 | mínimo: 3.98 | bundle: 0

[018d937e-f0ad-7094-b86c-d8fb32a1e6b4]
  historial: 650 registros
  precio actual: 6.9 | mínimo: 3.64 | bundle: 0

[018d937f-66a3-7379-b454-b05fe297ae90]
  historial: 69 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937e-ea28-7385-82ae-194da55d7217]
  historial: 131 registros
  precio actual: 7.49 | mínimo: 1 | bundle: 0

[018d937f-0ea6-732e-866d-75df62546c6b]
  historial: 305 registros
  precio actual: 7.49 | mínimo: 3.74 | bundle: 0

[018d937e-f52e-721f-a1f7-012ad9c06a8b]
  historial: 17 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-2404-7297-93fb-94b54bdb74e5]
  historial: 11 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937f-65ec-7270-86e5-b230afacae0b]
  historial: 0 registros
  precio actual: None | mínimo: None | bundle: 0

[018d937f-1989-71e0-8499-ccac3e7edbba]
  historial: 465 registros
  precio actual: 2.99 | mínimo: 1.19 | bundle: 0

[018d937e-fce3-7094-bf5f-033eef93575d]
  historial: 331 registros
  precio actual: 7.5 | mínimo: 2.24 | bundle: 0

[018d937e-fa14-7020-9111-93ad90d49695]
  historial: 17 registros
  precio actual: 15.89 | mínimo: 2.59 | bundle: 0

[018d9591-1da8-70cc-8fb1-899276510af2]
  historial: 47 registros
  precio actual: 27.99 | mínimo: 9.99 | bundle: 0

[018d937e-e9e5-72fa-a1dc-e7e0859183b6]
  historial: 202 registros
  precio actual: 5.99 | mínimo: 3.96 | bundle: 0

[018d937f-1624-7008-a279-b8bfb6e55610]
  historial: 66 registros
  precio actual: 17.19 | mínimo: 1.98 | bundle: 0

[018d937e-f0a4-725f-ad9f-2b5075961980]
  historial: 156 registros
  precio actual: 4.99 | mínimo: 1 | bundle: 0

[018d937f-51f4-727c-95c0-ba550d156c86]
  historial: 499 registros
  precio actual: 9.8 | mínimo: 3.59 | bundle: 0

[018d937e-f99a-7194-a303-07dd8f22d0b4]
  historial: 651 registros
  precio actual: 1.64 | mínimo: 1.45 | bundle: 0

[018d937f-1163-73c6-8a57-2660e40ceaf0]
  historial: 60 registros
  precio actual: 2.99 | mínimo: 2.99 | bundle: 0

[018d937f-246a-7339-8ccc-7bddae738345]
  historial: 180 registros
  precio actual: 8.99 | mínimo: 5 | bundle: 0

[018d937f-0e63-73bc-9df0-bde83d04cb52]
  historial: 12 registros
  precio actual: None | mínimo: 2.99 | bundle: 0

[018d937e-f092-7290-8d47-4870f06e148a]
  historial: 34 registros
  precio actual: None | mínimo: 3.99 | bundle: 0

[018d937f-03b7-718c-afcc-9fccfea4af66]
  historial: 10 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-62ef-71e8-990a-e31f12db98ef]
  historial: 28 registros
  precio actual: None | mínimo: 4.61 | bundle: 0

[018d937f-66a3-7379-b454-b05fe297ae90]
  historial: 69 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-299c-729c-bc8c-2c990e341c01]
  historial: 41 registros
  precio actual: 5.99 | mínimo: 2.33 | bundle: 0

[018d937f-26e9-7058-9337-3957883a16b7]
  historial: 31 registros
  precio actual: 8.39 | mínimo: 0.91 | bundle: 0

[018d937f-4a27-72c8-9837-8ec5e5e92932]
  historial: 45 registros
  precio actual: 7.99 | mínimo: 7.99 | bundle: 0

[018d937f-6bca-706d-9e69-8316170c379b]
  historial: 255 registros
  precio actual: 39.99 | mínimo: 32.95 | bundle: 0

[018e147e-9b32-7025-90af-981a785efddf]
  historial: 302 registros
  precio actual: 35.99 | mínimo: 30.16 | bundle: 0

[018dd0ec-ce78-7205-887b-cfc7b259ae00]
  historial: 72 registros
  precio actual: 14.99 | mínimo: 14.99 | bundle: 0

[018d937f-30fa-705e-8a3a-f39719bdde93]
  historial: 17 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-131c-708f-a973-4fc0767e382d]
  historial: 189 registros
  precio actual: 1.49 | mínimo: 1.11 | bundle: 0

[018d937f-2979-72d3-b30e-beb459582423]
  historial: 45 registros
  precio actual: None | mínimo: 3.19 | bundle: 0

[018d937f-060b-7399-9cd9-f894b77fb9a9]
  historial: 13 registros
  precio actual: None | mínimo: 2.25 | bundle: 0

[018d937f-00e8-729d-a917-e2f1d5bcc95d]
  historial: 386 registros
  precio actual: 4.99 | mínimo: 3.65 | bundle: 0

[018d937f-1d10-738e-a02f-67185816bae5]
  historial: 71 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-1ec4-7327-8a2a-99c60e52cd77]
  historial: 26 registros
  precio actual: None | mínimo: 9.79 | bundle: 0

[018d937e-f54c-7379-a57f-9ab6cdc42d20]
  historial: 202 registros
  precio actual: 7.49 | mínimo: 3.69 | bundle: 0

[018d937f-0184-7248-8d64-3c723c523111]
  historial: 182 registros
  precio actual: 11.99 | mínimo: 5.99 | bundle: 0

[018d937f-206b-7116-a860-da40b43874db]
  historial: 14 registros
  precio actual: None | mínimo: 2.49 | bundle: 0

[018d937f-4614-7311-8f5e-54720a2e73c2]
  historial: 114 registros
  precio actual: 3.99 | mínimo: 3.53 | bundle: 0

[018d9571-ca0b-7131-bb1e-05633a089597]
  historial: 28 registros
  precio actual: None | mínimo: 12.88 | bundle: 0

[018d937e-fde4-72ff-a7af-45e4955a8dd6]
  historial: 0 registros
  precio actual: None | mínimo: 19.99 | bundle: 0

[018d937e-fdb9-7203-a89a-1be9ff5e9467]
  historial: 7 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937e-ffba-7200-8bc4-99eccd424fa1]
  historial: 47 registros
  precio actual: 13.99 | mínimo: 11.99 | bundle: 0

[018d937f-2ee6-704c-8a25-f9606ccdf59a]
  historial: 18 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-5c96-7241-a70f-e8de1c1e0609]
  historial: 439 registros
  precio actual: 13.99 | mínimo: 7.96 | bundle: 0

[018d937e-ffb9-707b-a6dd-86c93c60b01f]
  historial: 412 registros
  precio actual: 2.82 | mínimo: 1.49 | bundle: 0

[018d937e-ff81-721c-b0a9-797caababfd7]
  historial: 175 registros
  precio actual: 8.99 | mínimo: 5 | bundle: 0

[018d937e-f4b1-72a4-8b98-1b65a43ec5bb]
  historial: 193 registros
  precio actual: 5.99 | mínimo: 2.92 | bundle: 0

[018d937f-22a3-73c2-b90f-0ea5c89c6ab9]
  historial: 27 registros
  precio actual: 0.89 | mínimo: 0.74 | bundle: 0

[018d937f-267f-730f-bba4-2d6b52801740]
  historial: 48 registros
  precio actual: None | mínimo: 2.99 | bundle: 0

[018d937f-209c-7223-8ead-671a11f25e7e]
  historial: 145 registros
  precio actual: 52.75 | mínimo: 5.99 | bundle: 0

[018d937f-07c2-7077-bebc-928c09f137d8]
  historial: 361 registros
  precio actual: 3.96 | mínimo: 3.49 | bundle: 0

[018d937f-62ef-71e8-990a-e31f12db98ef]
  historial: 28 registros
  precio actual: None | mínimo: 4.61 | bundle: 0

[018d937f-4adb-73a6-a9e5-94ff5f2b847b]
  historial: 54 registros
  precio actual: None | mínimo: 19.99 | bundle: 0

[018d937e-fdd8-73fc-b6f2-669d6969f960]
  historial: 180 registros
  precio actual: 7.49 | mínimo: 3.96 | bundle: 0

[018d937f-09dd-729b-88aa-5496f800b3bd]
  historial: 341 registros
  precio actual: 14.99 | mínimo: 10.75 | bundle: 0

[018d937f-1161-71bd-a3ba-b5f30a4b963b]
  historial: 194 registros
  precio actual: 3.36 | mínimo: 1.41 | bundle: 0

[018d937f-0fa4-71a4-a42e-9c52249465e9]
  historial: 14 registros
  precio actual: None | mínimo: 4.02 | bundle: 0

[018d937e-feb8-71a3-8819-21b3f9d400b8]
  historial: 1 registros
  precio actual: None | mínimo: 3.13 | bundle: 0

[018d937f-1225-735c-8589-9516bcc67da2]
  historial: 28 registros
  precio actual: 9.33 | mínimo: 1.09 | bundle: 0

[018d937f-2e9a-70fc-9c2e-565a87c8917b]
  historial: 385 registros
  precio actual: 7.99 | mínimo: 6.99 | bundle: 0

[018d937f-2133-7352-904c-8ee0741c3547]
  historial: 208 registros
  precio actual: 5.99 | mínimo: 2.4 | bundle: 0

[018d937f-2d6a-7013-adfa-096404f6d812]
  historial: 118 registros
  precio actual: 1.99 | mínimo: 1 | bundle: 0

[018d937f-679e-7276-b6f1-e59da609dd4b]
  historial: 314 registros
  precio actual: 29.99 | mínimo: 22.94 | bundle: 0

[018ffe0d-15a7-7247-bb3c-4e5e1980561f]
  historial: 776 registros
  precio actual: 37.49 | mínimo: 30.79 | bundle: 0

[018d937f-19a5-7057-bb6d-314d586e6dbc]
  historial: 0 registros
  precio actual: None | mínimo: 7.49 | bundle: 0

[018d937f-05be-7337-8877-c43351e767cb]
  historial: 24 registros
  precio actual: None | mínimo: 1.97 | bundle: 0

[018d937f-1d0a-704b-ae79-598acc6c23c5]
  historial: 9 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937f-2404-7297-93fb-94b54bdb74e5]
  historial: 11 registros
  precio actual: None | mínimo: 0.99 | bundle: 0

[018d937e-f04c-70ce-b011-e610ea57d321]
  historial: 619 registros
  precio actual: 1.56 | mínimo: 1.52 | bundle: 0

[018d937f-09a3-71c9-a2ee-f00c0abe998c]
  historial: 117 registros
  precio actual: 2.49 | mínimo: 1.49 | bundle: 0

[018d937f-08a6-7233-9599-69a9ea886bd9]
  historial: 112 registros
  precio actual: 9.99 | mínimo: 3.99 | bundle: 0

[018d956f-3d43-723c-a912-196164e7cf57]
  historial: 109 registros
  precio actual: None | mínimo: 1.11 | bundle: 0

[018d937f-192f-72c0-a5dc-81dce349ed7b]
  historial: 14 registros
  precio actual: 19.79 | mínimo: 9.15 | bundle: 0

[018d937f-0c9d-70bc-876a-059b7f1d0f54]
  historial: 126 registros
  precio actual: 29.99 | mínimo: 25.49 | bundle: 0

[018d937f-1b83-720e-b01b-745a61d426d8]
  historial: 15 registros
  precio actual: None | mínimo: 1.99 | bundle: 0

[018d937f-0c86-70e9-9298-ddf197875e33]
  historial: 134 registros
  precio actual: 9.99 | mínimo: 2.99 | bundle: 0

[018d937e-ff11-7011-8841-547a2015c0f1]
  historial: 236 registros
  precio actual: 9.99 | mínimo: 1.99 | bundle: 0

[018d937e-ff65-73f8-8d14-410ce85fa304]
  historial: 264 registros
  precio actual: 24.87 | mínimo: 2.39 | bundle: 0

[018d937f-0de8-7372-aa7a-fc902b95be0c]
  historial: 81 registros
  precio actual: 3.79 | mínimo: 1.99 | bundle: 0

[018d937f-30a6-70fa-994c-059be15778ad]
  historial: 3 registros
  precio actual: None | mínimo: 2.99 | bundle: 0

[018d937f-194c-7075-b7c9-a3c1fd30c467]
  historial: 385 registros
  precio actual: 17.99 | mínimo: 13.27 | bundle: 0

[018d937f-00cb-710a-9a4c-f7c1c558b97d]
  historial: 191 registros
  precio actual: 5.99 | mínimo: 2.4 | bundle: 0

[018d937e-ff7d-72cb-a737-8c4850fe85a2]
  historial: 413 registros
  precio actual: 1.99 | mínimo: 1.47 | bundle: 0

[018d937f-3aa4-70ce-a7f8-f766d6f6a9c1]
  historial: 22 registros
  precio actual: None | mínimo: 2.49 | bundle: 0

[018d937e-fd30-70ab-baba-665d4b6c0baf]
  historial: 38 registros
  precio actual: None | mínimo: 1.49 | bundle: 0

[018d937e-fd10-71e8-b295-945b5de8e4c2]
  historial: 70 registros
  precio actual: 16.49 | mínimo: 1.99 | bundle: 0

[018d937e-fd30-70ab-baba-665d4b44339a]
  historial: 155 registros
  precio actual: 5.99 | mínimo: 3.56 | bundle: 0

[018d937f-0ddf-7119-9337-aa96d8a36d39]
  historial: 0 registros
  precio actual: None | mínimo: None | bundle: 0

[018d937f-4adb-73a6-a9e5-94ff62f6265b]
  historial: 212 registros
  precio actual: 17.99 | mínimo: 16.16 | bundle: 0

[018d937f-2237-7301-a0d8-7074fb89a8d0]
  historial: 176 registros
  precio actual: 2.49 | mínimo: 2 | bundle: 0

[018d937f-1e66-7184-b1d7-1634c8fc9df4]
  historial: 224 registros
  precio actual: 5.99 | mínimo: 2.99 | bundle: 0

[018d937e-f8b9-702f-ab65-2b3ba5da16e6]
  historial: 0 registros
  precio actual: None | mínimo: 1 | bundle: 0

[018d937f-0e5f-720d-9312-46b065c9690c]
  historial: 3 registros
  precio actual: None | mínimo: 0.44 | bundle: 0

[018d937f-2077-7336-b125-3cd9641887eb]
  historial: 45 registros
  precio actual: 2.99 | mínimo: 2.39 | bundle: 0

[018d937e-f8b6-7306-b06c-689a8866f52a]
  historial: 2 registros
  precio actual: None | mínimo: 2.99 | bundle: 0

[018d937f-1304-7116-8fdf-d7aacd34cfb9]
  historial: 257 registros
  precio actual: None | mínimo: 7.37 | bundle: 0

[018d937f-6c88-722b-beeb-6e4c2273de5a]
  historial: 0 registros
  precio actual: None | mínimo: None | bundle: 0

[018d937f-1d1e-7172-a80b-3b57776007c8]
  historial: 193 registros
  precio actual: 5.99 | mínimo: 4.21 | bundle: 0

[018d937f-1609-7272-a6c7-61100a9fd54c]
  historial: 0 registros
  precio actual: None | mínimo: 23.45 | bundle: 0

[018d937f-2b4b-72f9-ab75-bc33784a295d]
  historial: 519 registros
  precio actual: 12.39 | mínimo: 9.13 | bundle: 0

[018d937f-6144-7057-ad1c-0e99a3a71797]
  historial: 354 registros
  precio actual: 7.56 | mínimo: 5.03 | bundle: 0

[018d937f-6b99-7077-9cf6-eacfce97587f]
  historial: 367 registros
  precio actual: 4.9 | mínimo: 3.35 | bundle: 0

[018d937e-f81a-7288-868c-49236397885a]
  historial: 482 registros
  precio actual: 5.05 | mínimo: 2.36 | bundle: 0

[018d937f-27c4-73f5-a546-99d6da398ae2]
  historial: 124 registros
  precio actual: 8.28 | mínimo: 1.59 | bundle: 0

[018d937f-3336-7249-be14-9c71dacce5db]
  historial: 15 registros
  precio actual: None | mínimo: 14.99 | bundle: 0

[018d937f-1cfa-70aa-a062-8eee73661b8e]
  historial: 34 registros
  precio actual: None | mínimo: 4.39 | bundle: 0

[018d937f-0651-7276-9c5d-9628dcc6b352]
  historial: 8 registros
  precio actual: None | mínimo: 1.49 | bundle: 0

[018d937f-57ce-723f-b7e7-7c7b5df93471]
  historial: 0 registros
  precio actual: None | mínimo: 14.99 | bundle: 0

[018d937f-15f9-7056-8edf-2e8fa4b8f357]
  historial: 653 registros
  precio actual: 18.89 | mínimo: 17.04 | bundle: 0

[018d937f-0e1e-70f5-85f9-797eb8bb0d39]
  historial: 28 registros
  precio actual: 19.79 | mínimo: 10.95 | bundle: 0

[018d937f-4ca6-7067-aee5-c1ed89a268f4]
  historial: 297 registros
  precio actual: 15.99 | mínimo: 9.86 | bundle: 0

[018d937f-6b99-7077-9cf6-eacfce97587f]
  historial: 367 registros
  precio actual: 4.9 | mínimo: 3.35 | bundle: 0

[018d937f-228e-7233-9b1b-1389c0b3a1e3]
  historial: 52 registros
  precio actual: 44.99 | mínimo: 13.99 | bundle: 0

[018d937e-ea5c-735e-ae2c-74a3c2a32f1d]
  historial: 29 registros
  precio actual: 19.79 | mínimo: 14.99 | bundle: 0

[018d9564-b6e9-73ad-884a-42cd82ab293c]
  historial: 276 registros
  precio actual: 11.86 | mínimo: 0.75 | bundle: 0

[018d937f-27b1-70c3-8978-7c37211c3dfa]
  historial: 131 registros
  precio actual: 7.49 | mínimo: 7.49 | bundle: 0

[018d937e-fd94-7238-a99b-14457502670c]
  historial: 453 registros
  precio actual: 7.65 | mínimo: 6.92 | bundle: 0

[018d937f-348e-7147-b777-b7754abcc2e7]
  historial: 216 registros

In [ ]:
# ver cuantos nos faltan
conn = sqlite3.connect(DB_PATH)
try:
    # Juegos sin vincular
    df_pendientes = pd.read_sql("""
        SELECT COUNT(*) AS sin_vincular
        FROM CAT_Juego j
        LEFT JOIN REL_Juego_ITAD r ON j.juego_id = r.juego_id
        WHERE j.id_steam IS NOT NULL
          AND r.itad_id_texto IS NULL
          AND j.categoria = 0
    """, conn)

    # Estado de tablas ITAD
    df_estado = pd.read_sql("""
        SELECT
            (SELECT COUNT(*) FROM CAT_ITAD_Juego)     AS ids_itad,
            (SELECT COUNT(*) FROM Datos_Actuales_ITAD) AS juegos_procesados,
            (SELECT COUNT(*) FROM Hist_Precios_ITAD)   AS registros_hist,
            (SELECT COUNT(*) FROM CAT_Tienda)           AS tiendas
    """, conn)

    display(df_pendientes)
    display(df_estado)
finally:
    conn.close()

   COUNT(*)
0         0

In [57]:
with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql("""
        SELECT
            COUNT(j.itad_id_texto)                  AS juegos_vinculados,
            COUNT(d.itad_id_texto)                  AS juegos_procesados,
            COUNT(h.itad_id_texto)                  AS juegos_con_historial,
            SUM(CASE WHEN d.precio_actual IS NOT NULL THEN 1 ELSE 0 END) AS con_precio_actual,
            SUM(CASE WHEN d.precio_minimo IS NOT NULL THEN 1 ELSE 0 END) AS con_precio_minimo,
            (SELECT COUNT(*) FROM Hist_Precios_ITAD) AS total_registros_hist
        FROM CAT_Juego j
        LEFT JOIN Datos_Actuales_ITAD d ON j.itad_id_texto = d.itad_id_texto
        LEFT JOIN (SELECT DISTINCT itad_id_texto FROM Hist_Precios_ITAD) h ON j.itad_id_texto = h.itad_id_texto
        WHERE j.itad_id_texto IS NOT NULL
    """, conn)
    display(df)

,juegos_vinculados,juegos_procesados,juegos_con_historial,con_precio_actual,con_precio_minimo,total_registros_hist
0,7172,195,158,156,155,2457

In [ ]:
conexion = sqlite3.connect(DB_PATH)
tablas = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';", conexion)
resumen = []
for tabla in tablas['name']:
    cantidad = pd.read_sql_query(f"SELECT COUNT(*) as Cantidad FROM {tabla};", conexion).iloc[0,0]
    resumen.append({'Nombre': tabla, 'Cantidad': cantidad})
df = pd.DataFrame(resumen).sort_values(by='Cantidad', ascending=False)
display(df)

conexion.close()

                     Nombre  Cantidad
20       Hist_Steam_Reviews    600194
17       REL_Juego_Etiqueta    127396
19     REL_Juegos_Similares    101550
18     REL_Juego_Plataforma     38040
10         REL_Juego_Genero     27717
11       REL_Juego_Tematica     21669
12           REL_Juego_Modo     17180
15         REL_Juego_Editor     14017
14  REL_Juego_Desarrollador     11338
13    REL_Juego_Perspectiva     11155
0                 CAT_Juego     10176
6               CAT_Empresa      6015
8              CAT_Etiqueta      3948
16     REL_Juego_Franquicia      3871
1             REL_Juego_DLC      1367
7            CAT_Franquicia       706
9            CAT_Plataforma       124
2                CAT_Genero        23
3              CAT_Tematica        22
5           CAT_Perspectiva         7
4            CAT_Modo_Juego         6
21        Hist_Precios_ITAD         0
22      Datos_Actuales_ITAD         0